#!/bin/sh
#
# recompile-test
#
# $Author: gutsche $
# $Date: 2004/03/17 18:59:37 $
# $Revision: 1.1 $
#
# $1: DEBUG=ON for debug compilation

# generating log file
export my_set=`date +_%y%m%d_%H%M%S`
export my_name=`echo "recompile_output$my_set.txt"`
touch $GUTCODEDIR/log/$my_name
rm -f $GUTCODEDIR/log/latest.txt
ln -s -f $GUTCODEDIR/log/$my_name $GUTCODEDIR/log/latest.txt

# starting script with logfile
time $GUTCODEDIR/scripts-analysis/project_recomp-test $1 > $GUTCODEDIR/log/$my_name 2>&1
