#!/bin/sh
#
# merge histogram-files
#
# input variables
#
# $1: version of data (subdir)
#
#
if [ -z $1 ]; then
    echo ""
    echo "Please give merged histogram-file"
    echo ""
    echo "Usage: merge [outputname]"
    echo ""
    exit
fi
#
merger.exe MERGE histos.root $1 mc/06e/c/dir02

