#!/bin/sh

cp mini_HeraII_0304p_Data_only_Dimuon_Finalversion_dimuon_0304p_dbothistos/*.root mini_HeraII_0307p_Data_dimuon_Dimuon_Finalversion_dbothistos_dimuon
cp mini_HeraII_05e_Data_only_Dimuon_Finalversion_dimuon_05e_dbothistos/*.root mini_HeraII_0307p_Data_dimuon_Dimuon_Finalversion_dbothistos_dimuon
cp mini_HeraII_0607p_Data_only_Dimuon_Finalversion_dimuon_0607p_dbothistos/*.root mini_HeraII_0307p_Data_dimuon_Dimuon_Finalversion_dbothistos_dimuon
cp mini_HeraII_06e_Data_only_Dimuon_Finalversion_dimuon_06e_dbothistos/*.root mini_HeraII_0307p_Data_dimuon_Dimuon_Finalversion_dbothistos_dimuon

