#!/bin/sh

cp mini_HeraII_0304p_Data_MC_Dimuon_Finalversion_muonjet_0304p_dbothistos/*.root mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_muonjet
cp mini_HeraII_05e_Data_MC_Dimuon_Finalversion_muonjet_05e_dbothistos/*.root mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_muonjet
cp mini_HeraII_0607p_Data_MC_Dimuon_Finalversion_muonjet_0607p_dbothistos/*.root mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_muonjet
cp mini_HeraII_06e_Data_MC_Dimuon_Finalversion_muonjet_06e_dbothistos/*.root mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_muonjet

