#!/bin/sh

cp ../mini_HeraII_0304p_Data_MC_Dimuon_Final_subsets_secvtx_0304p_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_subsets_secvtx
cp ../mini_HeraII_05e_Data_MC_Dimuon_Final_subsets_secvtx_05e_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_subsets_secvtx
cp ../mini_HeraII_06e_Data_MC_Dimuon_Final_subsets_secvtx_06e_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_subsets_secvtx
cp ../mini_HeraII_0607p_Data_MC_Dimuon_Final_subsets_secvtx_0607p_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_subsets_secvtx

