#!/bin/sh
#
# generate cards
#
# $1: cards template
#
if [ -z $1 ]; then
    echo ""
    echo "Please give cards file template"
    echo ""
    echo "Usage: generate_cards [template]"
    echo ""
    exit
fi
#
cardmaker.exe ANALUMIMCCCBARRAP data $1 147.33 05e mc_c_resrap.cards

