//
// File generated by rootcint at Fri Oct 24 10:57:57 2014

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GAnalysisDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GAnalysis_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_GAnalysis(void *p);
   static void deleteArray_GAnalysis(void *p);
   static void destruct_GAnalysis(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GAnalysis*)
   {
      ::GAnalysis *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GAnalysis >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GAnalysis", ::GAnalysis::Class_Version(), "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GAnalysis.h", 26,
                  typeid(::GAnalysis), DefineBehavior(ptr, ptr),
                  &::GAnalysis::Dictionary, isa_proxy, 0,
                  sizeof(::GAnalysis) );
      instance.SetDelete(&delete_GAnalysis);
      instance.SetDeleteArray(&deleteArray_GAnalysis);
      instance.SetDestructor(&destruct_GAnalysis);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GAnalysis*)
   {
      return GenerateInitInstanceLocal((::GAnalysis*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GAnalysis*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GAnalysis::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GAnalysis::Class_Name()
{
   return "GAnalysis";
}

//______________________________________________________________________________
const char *GAnalysis::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GAnalysis*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GAnalysis::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GAnalysis*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GAnalysis::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GAnalysis*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GAnalysis::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GAnalysis*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GAnalysis::Streamer(TBuffer &R__b)
{
   // Stream an object of class GAnalysis.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void GAnalysis::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class GAnalysis.
      TClass *R__cl = ::GAnalysis::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fEnableAnalysis", &fEnableAnalysis);
      R__insp.Inspect(R__cl, R__parent, "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__parent, "*fOutputFile", &fOutputFile);
      R__insp.Inspect(R__cl, R__parent, "*fHistogramDir", &fHistogramDir);
      R__insp.Inspect(R__cl, R__parent, "*fGeneralDir", &fGeneralDir);
      R__insp.Inspect(R__cl, R__parent, "*fHeaderTree", &fHeaderTree);
      R__insp.Inspect(R__cl, R__parent, "*fPhysicsObjs", &fPhysicsObjs);
      R__insp.Inspect(R__cl, R__parent, "*fHeader", &fHeader);
      R__insp.Inspect(R__cl, R__parent, "*fevlist", &fevlist);
      R__insp.Inspect(R__cl, R__parent, "*fevlist_use", &fevlist_use);
      R__insp.Inspect(R__cl, R__parent, "*ffile_ev", &ffile_ev);
      R__insp.Inspect(R__cl, R__parent, "fevlistfilename", &fevlistfilename);
      fevlistfilename.ShowMembers(R__insp, strcat(R__parent,"fevlistfilename.")); R__parent[R__ncp] = 0;
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_GAnalysis(void *p) {
      delete ((::GAnalysis*)p);
   }
   static void deleteArray_GAnalysis(void *p) {
      delete [] ((::GAnalysis*)p);
   }
   static void destruct_GAnalysis(void *p) {
      typedef ::GAnalysis current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GAnalysis

/********************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GAnalysisDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGAnalysisDict();

extern "C" void G__set_cpp_environmentGAnalysisDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GAnalysis.h");
  G__cpp_reset_tagtableGAnalysisDict();
}
#include <new>
extern "C" int G__cpp_dllrevGAnalysisDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GAnalysis */
static int G__GAnalysisDict_171_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GAnalysis* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new GAnalysis(*((TString*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) GAnalysis(*((TString*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysis));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GAnalysis*) G__getstructoffset())->DoAnalysis());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GAnalysis*) G__getstructoffset())->InitAnalysis(*((TString*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((GAnalysis*) G__getstructoffset())->PrintMessage(*((TString*) G__int(libp->para[0])));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GAnalysis*) G__getstructoffset())->Print(*((TString*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GAnalysis*) G__getstructoffset())->InitInclude());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GAnalysis*) G__getstructoffset())->ReadControlCards(*((TString*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GAnalysis*) G__getstructoffset())->ChainRootFiles());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GAnalysis*) G__getstructoffset())->CreateOutputFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GAnalysis*) G__getstructoffset())->GenerateHistogrammer());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GAnalysis*) G__getstructoffset())->FinalizeOutputFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((GAnalysis*) G__getstructoffset())->GetOutputFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((GAnalysis*) G__getstructoffset())->GetHistrogramDir());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((GAnalysis*) G__getstructoffset())->GetGeneralDir());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((GAnalysis*) G__getstructoffset())->GetFileName();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GAnalysis::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GAnalysis::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GAnalysis::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GAnalysis::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GAnalysis*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GAnalysis::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GAnalysis::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GAnalysis::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GAnalysisDict_171_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GAnalysis::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GAnalysisDict_171_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GAnalysis* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GAnalysis(*(GAnalysis*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysis));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GAnalysis G__TGAnalysis;
static int G__GAnalysisDict_171_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GAnalysis*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GAnalysis*) (soff+(sizeof(GAnalysis)*i)))->~G__TGAnalysis();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GAnalysis*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GAnalysis*) (soff))->~G__TGAnalysis();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GAnalysisDict_171_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GAnalysis* dest = (GAnalysis*) G__getstructoffset();
   *dest = *(GAnalysis*) libp->para[0].ref;
   const GAnalysis& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GAnalysis */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGAnalysisDict {
 public:
  G__Sizep2memfuncGAnalysisDict(): p(&G__Sizep2memfuncGAnalysisDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGAnalysisDict::*p)();
};

size_t G__get_sizep2memfuncGAnalysisDict()
{
  G__Sizep2memfuncGAnalysisDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGAnalysisDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysis))) {
     GAnalysis *G__Lderived;
     G__Lderived=(GAnalysis*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysis),G__get_linked_tagnum(&G__GAnalysisDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGAnalysisDict() {

   /* Setting up typedef entry */
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__GAnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GAnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GAnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GAnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GAnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GAnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GAnalysis */
static void G__setup_memvarGAnalysis(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysis));
   { GAnalysis *p; p=(GAnalysis*)0x1000; if (p) { }
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fEnableAnalysis=",0,"flag for enabling analysis loop");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TChain),-1,-1,4,"fChain=",0,"chain of root files from input path");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TFile),-1,-1,4,"fOutputFile=",0,"output file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TDirectory),-1,-1,4,"fHistogramDir=",0,"directorty in fOutputFile for histograms");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TDirectory),-1,-1,4,"fGeneralDir=",0,"directorty in fOutputFile for generalities");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TTree),-1,-1,4,"fHeaderTree=",0,"tree for header");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TList),-1,-1,4,"fPhysicsObjs=",0,"list of physics objects, attention, order matters");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysisHeader),-1,-1,4,"fHeader=",0,"header of analysis");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TEventList),-1,-1,4,"fevlist=",0,"generating an eventlist");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TEventList),-1,-1,4,"fevlist_use=",0,"using an existing eventlist");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TFile),-1,-1,4,"ffile_ev=",0,"file to store the generated eventlist in");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TString),-1,-1,4,"fevlistfilename=",0,"name of above file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GAnalysisDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGAnalysisDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGAnalysis(void) {
   /* GAnalysis */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysis));
   G__memfunc_setup("GAnalysis",907,G__GAnalysisDict_171_0_1, 105, G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysis), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - cardname", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoAnalysis",1015,G__GAnalysisDict_171_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitAnalysis",1240,G__GAnalysisDict_171_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "u 'TString' - 0 - cardname", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrintMessage",1234,G__GAnalysisDict_171_0_4, 117, G__get_linked_tagnum(&G__GAnalysisDictLN_TString), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Print",525,G__GAnalysisDict_171_0_5, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "u 'TString' - 0 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitInclude",1112,G__GAnalysisDict_171_0_6, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ReadControlCards",1610,G__GAnalysisDict_171_0_7, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "u 'TString' - 0 - cardname", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ChainRootFiles",1402,G__GAnalysisDict_171_0_8, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CreateOutputFile",1637,G__GAnalysisDict_171_0_9, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GenerateHistogrammer",2077,G__GAnalysisDict_171_0_10, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FinalizeOutputFile",1859,G__GAnalysisDict_171_0_11, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputFile",1329,G__GAnalysisDict_171_0_12, 85, G__get_linked_tagnum(&G__GAnalysisDictLN_TFile), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetHistrogramDir",1631,G__GAnalysisDict_171_0_13, 85, G__get_linked_tagnum(&G__GAnalysisDictLN_TDirectory), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetGeneralDir",1277,G__GAnalysisDict_171_0_14, 85, G__get_linked_tagnum(&G__GAnalysisDictLN_TDirectory), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetFileName",1057,G__GAnalysisDict_171_0_15, 117, G__get_linked_tagnum(&G__GAnalysisDictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__GAnalysisDict_171_0_16, 85, G__get_linked_tagnum(&G__GAnalysisDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GAnalysis::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GAnalysisDict_171_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GAnalysis::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GAnalysisDict_171_0_18, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GAnalysis::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GAnalysisDict_171_0_19, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GAnalysis::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GAnalysisDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GAnalysisDict_171_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GAnalysisDict_171_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GAnalysis::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GAnalysisDict_171_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GAnalysis::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GAnalysisDict_171_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GAnalysis::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GAnalysisDict_171_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GAnalysis::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GAnalysis", 907, G__GAnalysisDict_171_0_28, (int) ('i'), G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysis), -1, 0, 1, 1, 1, 0, "u 'GAnalysis' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GAnalysis", 1033, G__GAnalysisDict_171_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GAnalysisDict_171_0_30, (int) ('u'), G__get_linked_tagnum(&G__GAnalysisDictLN_GAnalysis), -1, 1, 1, 1, 1, 0, "u 'GAnalysis' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGAnalysisDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGAnalysisDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGAnalysisDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GAnalysisDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TDirectory = { "TDirectory" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TEventList = { "TEventList" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TChain = { "TChain" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_GAnalysisHeader = { "GAnalysisHeader" , 99 , -1 };
G__linked_taginfo G__GAnalysisDictLN_GAnalysis = { "GAnalysis" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGAnalysisDict() {
  G__GAnalysisDictLN_TClass.tagnum = -1 ;
  G__GAnalysisDictLN_TBuffer.tagnum = -1 ;
  G__GAnalysisDictLN_TDirectory.tagnum = -1 ;
  G__GAnalysisDictLN_TMemberInspector.tagnum = -1 ;
  G__GAnalysisDictLN_TObject.tagnum = -1 ;
  G__GAnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GAnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GAnalysisDictLN_TList.tagnum = -1 ;
  G__GAnalysisDictLN_TString.tagnum = -1 ;
  G__GAnalysisDictLN_TEventList.tagnum = -1 ;
  G__GAnalysisDictLN_TFile.tagnum = -1 ;
  G__GAnalysisDictLN_TChain.tagnum = -1 ;
  G__GAnalysisDictLN_TTree.tagnum = -1 ;
  G__GAnalysisDictLN_GAnalysisHeader.tagnum = -1 ;
  G__GAnalysisDictLN_GAnalysis.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGAnalysisDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TDirectory);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TList);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TString);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TEventList);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TChain);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_GAnalysisHeader);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GAnalysisDictLN_GAnalysis),sizeof(GAnalysis),-1,62464,"main analysis class",G__setup_memvarGAnalysis,G__setup_memfuncGAnalysis);
}
extern "C" void G__cpp_setupGAnalysisDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGAnalysisDict()");
  G__set_cpp_environmentGAnalysisDict();
  G__cpp_setup_tagtableGAnalysisDict();

  G__cpp_setup_inheritanceGAnalysisDict();

  G__cpp_setup_typetableGAnalysisDict();

  G__cpp_setup_memvarGAnalysisDict();

  G__cpp_setup_memfuncGAnalysisDict();
  G__cpp_setup_globalGAnalysisDict();
  G__cpp_setup_funcGAnalysisDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGAnalysisDict();
  return;
}
class G__cpp_setup_initGAnalysisDict {
  public:
    G__cpp_setup_initGAnalysisDict() { G__add_setup_func("GAnalysisDict",(G__incsetup)(&G__cpp_setupGAnalysisDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGAnalysisDict() { G__remove_setup_func("GAnalysisDict"); }
};
G__cpp_setup_initGAnalysisDict G__cpp_setup_initializerGAnalysisDict;

