/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GDIMuonsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GDIMuonsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGDIMuonsDict();
extern void G__cpp_setup_inheritanceGDIMuonsDict();
extern void G__cpp_setup_typetableGDIMuonsDict();
extern void G__cpp_setup_memvarGDIMuonsDict();
extern void G__cpp_setup_globalGDIMuonsDict();
extern void G__cpp_setup_memfuncGDIMuonsDict();
extern void G__cpp_setup_funcGDIMuonsDict();
extern void G__set_cpp_environmentGDIMuonsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GDIMuons.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GDIMuonsDictLN_TClass;
extern G__linked_taginfo G__GDIMuonsDictLN_TBuffer;
extern G__linked_taginfo G__GDIMuonsDictLN_TMemberInspector;
extern G__linked_taginfo G__GDIMuonsDictLN_TObject;
extern G__linked_taginfo G__GDIMuonsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GDIMuonsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GDIMuonsDictLN_TString;
extern G__linked_taginfo G__GDIMuonsDictLN_TClonesArray;
extern G__linked_taginfo G__GDIMuonsDictLN_TH1D;
extern G__linked_taginfo G__GDIMuonsDictLN_GDIMuon;
extern G__linked_taginfo G__GDIMuonsDictLN_GPhysObj;
extern G__linked_taginfo G__GDIMuonsDictLN_GDIMuons;

/* STUB derived class for protected member access */
