//
// File generated by rootcint at Fri Oct 24 10:57:58 2014

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GGeneralDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GGeneral_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_GGeneral(void *p = 0);
   static void *newArray_GGeneral(Long_t size, void *p);
   static void delete_GGeneral(void *p);
   static void deleteArray_GGeneral(void *p);
   static void destruct_GGeneral(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GGeneral*)
   {
      ::GGeneral *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GGeneral >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GGeneral", ::GGeneral::Class_Version(), "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GGeneral.h", 42,
                  typeid(::GGeneral), DefineBehavior(ptr, ptr),
                  &::GGeneral::Dictionary, isa_proxy, 0,
                  sizeof(::GGeneral) );
      instance.SetNew(&new_GGeneral);
      instance.SetNewArray(&newArray_GGeneral);
      instance.SetDelete(&delete_GGeneral);
      instance.SetDeleteArray(&deleteArray_GGeneral);
      instance.SetDestructor(&destruct_GGeneral);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GGeneral*)
   {
      return GenerateInitInstanceLocal((::GGeneral*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GGeneral*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GGeneral::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GGeneral::Class_Name()
{
   return "GGeneral";
}

//______________________________________________________________________________
const char *GGeneral::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GGeneral*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GGeneral::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GGeneral*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GGeneral::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GGeneral*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GGeneral::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GGeneral*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GGeneral::Streamer(TBuffer &R__b)
{
   // Stream an object of class GGeneral.

   GPhysObj::Streamer(R__b);
}

//______________________________________________________________________________
void GGeneral::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class GGeneral.
      TClass *R__cl = ::GGeneral::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fPeriod", &fPeriod);
      R__insp.Inspect(R__cl, R__parent, "f96p_low", &f96p_low);
      R__insp.Inspect(R__cl, R__parent, "f96p_up", &f96p_up);
      R__insp.Inspect(R__cl, R__parent, "f97p_low", &f97p_low);
      R__insp.Inspect(R__cl, R__parent, "f97p_up", &f97p_up);
      R__insp.Inspect(R__cl, R__parent, "f98e_low", &f98e_low);
      R__insp.Inspect(R__cl, R__parent, "f98e_up", &f98e_up);
      R__insp.Inspect(R__cl, R__parent, "f99e_low", &f99e_low);
      R__insp.Inspect(R__cl, R__parent, "f99e_up", &f99e_up);
      R__insp.Inspect(R__cl, R__parent, "f99p_low", &f99p_low);
      R__insp.Inspect(R__cl, R__parent, "f99p_up", &f99p_up);
      R__insp.Inspect(R__cl, R__parent, "f00p_low", &f00p_low);
      R__insp.Inspect(R__cl, R__parent, "f00p_up", &f00p_up);
      R__insp.Inspect(R__cl, R__parent, "f02p_low", &f02p_low);
      R__insp.Inspect(R__cl, R__parent, "f02p_up", &f02p_up);
      R__insp.Inspect(R__cl, R__parent, "f03p_low", &f03p_low);
      R__insp.Inspect(R__cl, R__parent, "f03p_up", &f03p_up);
      R__insp.Inspect(R__cl, R__parent, "f04p_low", &f04p_low);
      R__insp.Inspect(R__cl, R__parent, "f04p_up", &f04p_up);
      R__insp.Inspect(R__cl, R__parent, "f05e_low", &f05e_low);
      R__insp.Inspect(R__cl, R__parent, "f05e_up", &f05e_up);
      R__insp.Inspect(R__cl, R__parent, "f06e_low", &f06e_low);
      R__insp.Inspect(R__cl, R__parent, "f06e_up", &f06e_up);
      R__insp.Inspect(R__cl, R__parent, "f06p_low", &f06p_low);
      R__insp.Inspect(R__cl, R__parent, "f06p_up", &f06p_up);
      R__insp.Inspect(R__cl, R__parent, "f07p_low", &f07p_low);
      R__insp.Inspect(R__cl, R__parent, "f07p_up", &f07p_up);
      R__insp.Inspect(R__cl, R__parent, "*f96p_uncut", &f96p_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f97p_uncut", &f97p_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f98e_uncut", &f98e_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f99e_uncut", &f99e_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f99p_uncut", &f99p_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f00p_uncut", &f00p_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f02p_uncut", &f02p_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f03p_uncut", &f03p_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f04p_uncut", &f04p_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f05e_uncut", &f05e_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f06e_uncut", &f06e_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f06p_uncut", &f06p_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f07p_uncut", &f07p_uncut);
      R__insp.Inspect(R__cl, R__parent, "*f96p", &f96p);
      R__insp.Inspect(R__cl, R__parent, "*f97p", &f97p);
      R__insp.Inspect(R__cl, R__parent, "*f98e", &f98e);
      R__insp.Inspect(R__cl, R__parent, "*f99e", &f99e);
      R__insp.Inspect(R__cl, R__parent, "*f99p", &f99p);
      R__insp.Inspect(R__cl, R__parent, "*f00p", &f00p);
      R__insp.Inspect(R__cl, R__parent, "*f02p", &f02p);
      R__insp.Inspect(R__cl, R__parent, "*f03p", &f03p);
      R__insp.Inspect(R__cl, R__parent, "*f04p", &f04p);
      R__insp.Inspect(R__cl, R__parent, "*f05e", &f05e);
      R__insp.Inspect(R__cl, R__parent, "*f06e", &f06e);
      R__insp.Inspect(R__cl, R__parent, "*f06p", &f06p);
      R__insp.Inspect(R__cl, R__parent, "*f07p", &f07p);
      R__insp.Inspect(R__cl, R__parent, "*f96p_Taked", &f96p_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f97p_Taked", &f97p_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f98e_Taked", &f98e_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f99e_Taked", &f99e_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f99p_Taked", &f99p_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f00p_Taked", &f00p_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f02p_Taked", &f02p_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f03p_Taked", &f03p_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f04p_Taked", &f04p_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f05e_Taked", &f05e_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f06e_Taked", &f06e_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f06p_Taked", &f06p_Taked);
      R__insp.Inspect(R__cl, R__parent, "*f07p_Taked", &f07p_Taked);
      R__insp.Inspect(R__cl, R__parent, "*fWeight_uncut", &fWeight_uncut);
      R__insp.Inspect(R__cl, R__parent, "*fWeight", &fWeight);
      GPhysObj::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_GGeneral(void *p) {
      return  p ? new(p) ::GGeneral : new ::GGeneral;
   }
   static void *newArray_GGeneral(Long_t nElements, void *p) {
      return p ? new(p) ::GGeneral[nElements] : new ::GGeneral[nElements];
   }
   // Wrapper around operator delete
   static void delete_GGeneral(void *p) {
      delete ((::GGeneral*)p);
   }
   static void deleteArray_GGeneral(void *p) {
      delete [] ((::GGeneral*)p);
   }
   static void destruct_GGeneral(void *p) {
      typedef ::GGeneral current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GGeneral

/********************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GGeneralDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGGeneralDict();

extern "C" void G__set_cpp_environmentGGeneralDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GGeneral.h");
  G__cpp_reset_tagtableGGeneralDict();
}
#include <new>
extern "C" int G__cpp_dllrevGGeneralDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GGeneral */
static int G__GGeneralDict_165_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GGeneral* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GGeneral[n];
     } else {
       p = new((void*) gvp) GGeneral[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GGeneral;
     } else {
       p = new((void*) gvp) GGeneral;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GGeneral*) G__getstructoffset())->CheckRunPeriod());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GGeneral*) G__getstructoffset())->CheckProperties());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get96p_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get96p_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get97p_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get97p_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get98e_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get98e_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get99e_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get99e_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get99p_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get99p_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get00p_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get00p_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get02p_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get02p_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get03p_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get03p_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get04p_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get04p_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get05e_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get05e_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get06e_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get06e_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get06p_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get06p_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get07p_low());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->Get07p_up());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GGeneral*) G__getstructoffset())->GetRunPeriod());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GGeneral::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GGeneral::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GGeneral::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GGeneral::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GGeneral*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GGeneral::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GGeneral::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GGeneral::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GGeneralDict_165_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GGeneral::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GGeneralDict_165_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GGeneral* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GGeneral(*(GGeneral*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GGeneral G__TGGeneral;
static int G__GGeneralDict_165_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GGeneral*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GGeneral*) (soff+(sizeof(GGeneral)*i)))->~G__TGGeneral();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GGeneral*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GGeneral*) (soff))->~G__TGGeneral();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GGeneralDict_165_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GGeneral* dest = (GGeneral*) G__getstructoffset();
   *dest = *(GGeneral*) libp->para[0].ref;
   const GGeneral& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GGeneral */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGGeneralDict {
 public:
  G__Sizep2memfuncGGeneralDict(): p(&G__Sizep2memfuncGGeneralDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGGeneralDict::*p)();
};

size_t G__get_sizep2memfuncGGeneralDict()
{
  G__Sizep2memfuncGGeneralDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGGeneralDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral))) {
     GGeneral *G__Lderived;
     G__Lderived=(GGeneral*)0x1000;
     {
       GPhysObj *G__Lpbase=(GPhysObj*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral),G__get_linked_tagnum(&G__GGeneralDictLN_GPhysObj),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral),G__get_linked_tagnum(&G__GGeneralDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGGeneralDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__GGeneralDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GGeneralDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GGeneralDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GGeneralDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GGeneralDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GGeneralDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GGeneral */
static void G__setup_memvarGGeneral(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral));
   { GGeneral *p; p=(GGeneral*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_EZRunPeriod),-1,-1,4,"fPeriod=",0,"run period");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f96p_low=",0,"lower border of 96p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f96p_up=",0,"upper border of 96p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f97p_low=",0,"lower border of 97p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f97p_up=",0,"upper border of 97p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f98e_low=",0,"lower border of 98e' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f98e_up=",0,"upper border of 98e' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f99e_low=",0,"lower border of 99e' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f99e_up=",0,"upper border of 99e' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f99p_low=",0,"lower border of 99p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f99p_up=",0,"upper border of 99p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f00p_low=",0,"lower border of 00p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f00p_up=",0,"upper border of 00p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f02p_low=",0,"lower border of 02p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f02p_up=",0,"upper border of 02p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f03p_low=",0,"lower border of 03p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f03p_up=",0,"upper border of 03p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f04p_low=",0,"lower border of 04p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f04p_up=",0,"upper border of 04p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f05e_low=",0,"lower border of 05e' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f05e_up=",0,"upper border of 05e' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f06e_low=",0,"lower border of 06e' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f06e_up=",0,"upper border of 06e' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f06p_low=",0,"lower border of 06p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f06p_up=",0,"upper border of 06p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f07p_low=",0,"lower border of 07p' runrange");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"f07p_up=",0,"upper border of 07p' runrange");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f96p_uncut=",0,"uncut run summary plot for 96p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f97p_uncut=",0,"uncut run summary plot for 97p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f98e_uncut=",0,"uncut run summary plot for 98e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f99e_uncut=",0,"uncut run summary plot for 99e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f99p_uncut=",0,"uncut run summary plot for 99p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f00p_uncut=",0,"uncut run summary plot for 00p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f02p_uncut=",0,"uncut run summary plot for 02p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f03p_uncut=",0,"uncut run summary plot for 03p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f04p_uncut=",0,"uncut run summary plot for 04p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f05e_uncut=",0,"uncut run summary plot for 05e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f06e_uncut=",0,"uncut run summary plot for 06e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f06p_uncut=",0,"uncut run summary plot for 06p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f07p_uncut=",0,"uncut run summary plot for 07p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f96p=",0,"run summary plot for 96p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f97p=",0,"run summary plot for 97p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f98e=",0,"run summary plot for 98e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f99e=",0,"run summary plot for 99e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f99p=",0,"run summary plot for 99p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f00p=",0,"run summary plot for 00p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f02p=",0,"run summary plot for 02p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f03p=",0,"run summary plot for 03p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f04p=",0,"run summary plot for 04p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f05e=",0,"run summary plot for 05e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f06e=",0,"run summary plot for 06e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f06p=",0,"run summary plot for 06p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f07p=",0,"run summary plot for 07p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f96p_Taked=",0,"run summary plot for 96p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f97p_Taked=",0,"run summary plot for 97p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f98e_Taked=",0,"run summary plot for 98e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f99e_Taked=",0,"run summary plot for 99e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f99p_Taked=",0,"run summary plot for 99p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f00p_Taked=",0,"run summary plot for 00p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f02p_Taked=",0,"run summary plot for 02p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f03p_Taked=",0,"run summary plot for 03p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f04p_Taked=",0,"run summary plot for 04p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f05e_Taked=",0,"run summary plot for 05e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f06e_Taked=",0,"run summary plot for 06e");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f06p_Taked=",0,"run summary plot for 06p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"f07p_Taked=",0,"run summary plot for 07p");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"fWeight_uncut=",0,"uncut event weight");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TH1D),-1,-1,4,"fWeight=",0,"event weight");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GGeneralDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGGeneralDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGGeneral(void) {
   /* GGeneral */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral));
   G__memfunc_setup("GGeneral",773,G__GGeneralDict_165_0_1, 105, G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateControl",1333,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FillControl",1128,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CreateGeneral",1298,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FillGeneral",1093,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Do",179,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CheckRunPeriod",1398,G__GGeneralDict_165_0_7, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CheckProperties",1547,G__GGeneralDict_165_0_8, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reset",515,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrintMessage",1234,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__GGeneralDictLN_TString), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "u 'TString' - 0 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get96p_low",944,G__GGeneralDict_165_0_12, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get96p_up",835,G__GGeneralDict_165_0_13, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get97p_low",945,G__GGeneralDict_165_0_14, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get97p_up",836,G__GGeneralDict_165_0_15, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get98e_low",935,G__GGeneralDict_165_0_16, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get98e_up",826,G__GGeneralDict_165_0_17, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get99e_low",936,G__GGeneralDict_165_0_18, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get99e_up",827,G__GGeneralDict_165_0_19, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get99p_low",947,G__GGeneralDict_165_0_20, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get99p_up",838,G__GGeneralDict_165_0_21, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get00p_low",929,G__GGeneralDict_165_0_22, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get00p_up",820,G__GGeneralDict_165_0_23, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get02p_low",931,G__GGeneralDict_165_0_24, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get02p_up",822,G__GGeneralDict_165_0_25, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get03p_low",932,G__GGeneralDict_165_0_26, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get03p_up",823,G__GGeneralDict_165_0_27, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get04p_low",933,G__GGeneralDict_165_0_28, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get04p_up",824,G__GGeneralDict_165_0_29, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get05e_low",923,G__GGeneralDict_165_0_30, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get05e_up",814,G__GGeneralDict_165_0_31, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get06e_low",924,G__GGeneralDict_165_0_32, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get06e_up",815,G__GGeneralDict_165_0_33, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get06p_low",935,G__GGeneralDict_165_0_34, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get06p_up",826,G__GGeneralDict_165_0_35, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get07p_low",936,G__GGeneralDict_165_0_36, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Get07p_up",827,G__GGeneralDict_165_0_37, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetRunPeriod",1208,G__GGeneralDict_165_0_38, 105, G__get_linked_tagnum(&G__GGeneralDictLN_EZRunPeriod), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__GGeneralDict_165_0_39, 85, G__get_linked_tagnum(&G__GGeneralDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GGeneral::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GGeneralDict_165_0_40, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GGeneral::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GGeneralDict_165_0_41, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GGeneral::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GGeneralDict_165_0_42, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GGeneral::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GGeneralDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GGeneralDict_165_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GGeneralDict_165_0_47, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GGeneral::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GGeneralDict_165_0_48, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GGeneral::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GGeneralDict_165_0_49, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GGeneral::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GGeneralDict_165_0_50, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GGeneral::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GGeneral", 773, G__GGeneralDict_165_0_51, (int) ('i'), G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral), -1, 0, 1, 1, 1, 0, "u 'GGeneral' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GGeneral", 899, G__GGeneralDict_165_0_52, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GGeneralDict_165_0_53, (int) ('u'), G__get_linked_tagnum(&G__GGeneralDictLN_GGeneral), -1, 1, 1, 1, 1, 0, "u 'GGeneral' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGGeneralDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGGeneralDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGGeneralDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GGeneralDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GGeneralDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GGeneralDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GGeneralDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GGeneralDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GGeneralDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GGeneralDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__GGeneralDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__GGeneralDictLN_GPhysObj = { "GPhysObj" , 99 , -1 };
G__linked_taginfo G__GGeneralDictLN_EZRunPeriod = { "EZRunPeriod" , 101 , -1 };
G__linked_taginfo G__GGeneralDictLN_GGeneral = { "GGeneral" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGGeneralDict() {
  G__GGeneralDictLN_TClass.tagnum = -1 ;
  G__GGeneralDictLN_TBuffer.tagnum = -1 ;
  G__GGeneralDictLN_TMemberInspector.tagnum = -1 ;
  G__GGeneralDictLN_TObject.tagnum = -1 ;
  G__GGeneralDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GGeneralDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GGeneralDictLN_TString.tagnum = -1 ;
  G__GGeneralDictLN_TH1D.tagnum = -1 ;
  G__GGeneralDictLN_GPhysObj.tagnum = -1 ;
  G__GGeneralDictLN_EZRunPeriod.tagnum = -1 ;
  G__GGeneralDictLN_GGeneral.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGGeneralDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_TString);
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_GPhysObj);
   G__get_linked_tagnum_fwd(&G__GGeneralDictLN_EZRunPeriod);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GGeneralDictLN_GGeneral),sizeof(GGeneral),-1,29952,"General class for general properties",G__setup_memvarGGeneral,G__setup_memfuncGGeneral);
}
extern "C" void G__cpp_setupGGeneralDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGGeneralDict()");
  G__set_cpp_environmentGGeneralDict();
  G__cpp_setup_tagtableGGeneralDict();

  G__cpp_setup_inheritanceGGeneralDict();

  G__cpp_setup_typetableGGeneralDict();

  G__cpp_setup_memvarGGeneralDict();

  G__cpp_setup_memfuncGGeneralDict();
  G__cpp_setup_globalGGeneralDict();
  G__cpp_setup_funcGGeneralDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGGeneralDict();
  return;
}
class G__cpp_setup_initGGeneralDict {
  public:
    G__cpp_setup_initGGeneralDict() { G__add_setup_func("GGeneralDict",(G__incsetup)(&G__cpp_setupGGeneralDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGGeneralDict() { G__remove_setup_func("GGeneralDict"); }
};
G__cpp_setup_initGGeneralDict G__cpp_setup_initializerGGeneralDict;

