/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GGeneralDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GGeneralDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGGeneralDict();
extern void G__cpp_setup_inheritanceGGeneralDict();
extern void G__cpp_setup_typetableGGeneralDict();
extern void G__cpp_setup_memvarGGeneralDict();
extern void G__cpp_setup_globalGGeneralDict();
extern void G__cpp_setup_memfuncGGeneralDict();
extern void G__cpp_setup_funcGGeneralDict();
extern void G__set_cpp_environmentGGeneralDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GGeneral.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GGeneralDictLN_TClass;
extern G__linked_taginfo G__GGeneralDictLN_TBuffer;
extern G__linked_taginfo G__GGeneralDictLN_TMemberInspector;
extern G__linked_taginfo G__GGeneralDictLN_TObject;
extern G__linked_taginfo G__GGeneralDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GGeneralDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GGeneralDictLN_TString;
extern G__linked_taginfo G__GGeneralDictLN_TH1D;
extern G__linked_taginfo G__GGeneralDictLN_GPhysObj;
extern G__linked_taginfo G__GGeneralDictLN_EZRunPeriod;
extern G__linked_taginfo G__GGeneralDictLN_GGeneral;

/* STUB derived class for protected member access */
