/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GImpactFitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GImpactFitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGImpactFitDict();
extern void G__cpp_setup_inheritanceGImpactFitDict();
extern void G__cpp_setup_typetableGImpactFitDict();
extern void G__cpp_setup_memvarGImpactFitDict();
extern void G__cpp_setup_globalGImpactFitDict();
extern void G__cpp_setup_memfuncGImpactFitDict();
extern void G__cpp_setup_funcGImpactFitDict();
extern void G__set_cpp_environmentGImpactFitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GImpactFit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GImpactFitDictLN_TClass;
extern G__linked_taginfo G__GImpactFitDictLN_TBuffer;
extern G__linked_taginfo G__GImpactFitDictLN_TMemberInspector;
extern G__linked_taginfo G__GImpactFitDictLN_TObject;
extern G__linked_taginfo G__GImpactFitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GImpactFitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GImpactFitDictLN_TString;
extern G__linked_taginfo G__GImpactFitDictLN_GImpactFit;

/* STUB derived class for protected member access */
