/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GMCsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GMCsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGMCsDict();
extern void G__cpp_setup_inheritanceGMCsDict();
extern void G__cpp_setup_typetableGMCsDict();
extern void G__cpp_setup_memvarGMCsDict();
extern void G__cpp_setup_globalGMCsDict();
extern void G__cpp_setup_memfuncGMCsDict();
extern void G__cpp_setup_funcGMCsDict();
extern void G__set_cpp_environmentGMCsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GMCs.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GMCsDictLN_TClass;
extern G__linked_taginfo G__GMCsDictLN_TBuffer;
extern G__linked_taginfo G__GMCsDictLN_TMemberInspector;
extern G__linked_taginfo G__GMCsDictLN_TObject;
extern G__linked_taginfo G__GMCsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GMCsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GMCsDictLN_TString;
extern G__linked_taginfo G__GMCsDictLN_TClonesArray;
extern G__linked_taginfo G__GMCsDictLN_TH1D;
extern G__linked_taginfo G__GMCsDictLN_TH2D;
extern G__linked_taginfo G__GMCsDictLN_GMuon;
extern G__linked_taginfo G__GMCsDictLN_GJet;
extern G__linked_taginfo G__GMCsDictLN_GDIMuon;
extern G__linked_taginfo G__GMCsDictLN_GPhysObj;
extern G__linked_taginfo G__GMCsDictLN_GMC;
extern G__linked_taginfo G__GMCsDictLN_GMCVertex;
extern G__linked_taginfo G__GMCsDictLN_GMCs;

/* STUB derived class for protected member access */
