/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GMergerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GMergerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGMergerDict();
extern void G__cpp_setup_inheritanceGMergerDict();
extern void G__cpp_setup_typetableGMergerDict();
extern void G__cpp_setup_memvarGMergerDict();
extern void G__cpp_setup_globalGMergerDict();
extern void G__cpp_setup_memfuncGMergerDict();
extern void G__cpp_setup_funcGMergerDict();
extern void G__set_cpp_environmentGMergerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GMerger.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GMergerDictLN_TClass;
extern G__linked_taginfo G__GMergerDictLN_TBuffer;
extern G__linked_taginfo G__GMergerDictLN_TMemberInspector;
extern G__linked_taginfo G__GMergerDictLN_TObject;
extern G__linked_taginfo G__GMergerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GMergerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GMergerDictLN_TList;
extern G__linked_taginfo G__GMergerDictLN_TString;
extern G__linked_taginfo G__GMergerDictLN_TFile;
extern G__linked_taginfo G__GMergerDictLN_GMerger;

/* STUB derived class for protected member access */
