/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GMJMatchDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GMJMatchDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGMJMatchDict();
extern void G__cpp_setup_inheritanceGMJMatchDict();
extern void G__cpp_setup_typetableGMJMatchDict();
extern void G__cpp_setup_memvarGMJMatchDict();
extern void G__cpp_setup_globalGMJMatchDict();
extern void G__cpp_setup_memfuncGMJMatchDict();
extern void G__cpp_setup_funcGMJMatchDict();
extern void G__set_cpp_environmentGMJMatchDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GMJMatch.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GMJMatchDictLN_TClass;
extern G__linked_taginfo G__GMJMatchDictLN_TBuffer;
extern G__linked_taginfo G__GMJMatchDictLN_TMemberInspector;
extern G__linked_taginfo G__GMJMatchDictLN_TObject;
extern G__linked_taginfo G__GMJMatchDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GMJMatchDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GMJMatchDictLN_TString;
extern G__linked_taginfo G__GMJMatchDictLN_GJet;
extern G__linked_taginfo G__GMJMatchDictLN_GMuon;
extern G__linked_taginfo G__GMJMatchDictLN_EZMJMatchType;
extern G__linked_taginfo G__GMJMatchDictLN_GMJMatch;

/* STUB derived class for protected member access */
