/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GMuonsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GMuonsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGMuonsDict();
extern void G__cpp_setup_inheritanceGMuonsDict();
extern void G__cpp_setup_typetableGMuonsDict();
extern void G__cpp_setup_memvarGMuonsDict();
extern void G__cpp_setup_globalGMuonsDict();
extern void G__cpp_setup_memfuncGMuonsDict();
extern void G__cpp_setup_funcGMuonsDict();
extern void G__set_cpp_environmentGMuonsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GMuons.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GMuonsDictLN_TClass;
extern G__linked_taginfo G__GMuonsDictLN_TBuffer;
extern G__linked_taginfo G__GMuonsDictLN_TMemberInspector;
extern G__linked_taginfo G__GMuonsDictLN_TObject;
extern G__linked_taginfo G__GMuonsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GMuonsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GMuonsDictLN_TString;
extern G__linked_taginfo G__GMuonsDictLN_TClonesArray;
extern G__linked_taginfo G__GMuonsDictLN_TH1D;
extern G__linked_taginfo G__GMuonsDictLN_TH2D;
extern G__linked_taginfo G__GMuonsDictLN_GMuon;
extern G__linked_taginfo G__GMuonsDictLN_GPhysObj;
extern G__linked_taginfo G__GMuonsDictLN_TRandom;
extern G__linked_taginfo G__GMuonsDictLN_GMuonEfficiency;
extern G__linked_taginfo G__GMuonsDictLN_GMuons;

/* STUB derived class for protected member access */
