//
// File generated by rootcint at Thu Oct 23 10:41:37 2014

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GMuonEfficiencyDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GMuonEfficiency_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_GMuonEfficiency(void *p = 0);
   static void *newArray_GMuonEfficiency(Long_t size, void *p);
   static void delete_GMuonEfficiency(void *p);
   static void deleteArray_GMuonEfficiency(void *p);
   static void destruct_GMuonEfficiency(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GMuonEfficiency*)
   {
      ::GMuonEfficiency *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GMuonEfficiency >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GMuonEfficiency", ::GMuonEfficiency::Class_Version(), "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GMuonEfficiency.h", 21,
                  typeid(::GMuonEfficiency), DefineBehavior(ptr, ptr),
                  &::GMuonEfficiency::Dictionary, isa_proxy, 0,
                  sizeof(::GMuonEfficiency) );
      instance.SetNew(&new_GMuonEfficiency);
      instance.SetNewArray(&newArray_GMuonEfficiency);
      instance.SetDelete(&delete_GMuonEfficiency);
      instance.SetDeleteArray(&deleteArray_GMuonEfficiency);
      instance.SetDestructor(&destruct_GMuonEfficiency);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GMuonEfficiency*)
   {
      return GenerateInitInstanceLocal((::GMuonEfficiency*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GMuonEfficiency*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GMuonEfficiency::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GMuonEfficiency::Class_Name()
{
   return "GMuonEfficiency";
}

//______________________________________________________________________________
const char *GMuonEfficiency::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GMuonEfficiency*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GMuonEfficiency::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GMuonEfficiency*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GMuonEfficiency::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GMuonEfficiency*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GMuonEfficiency::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GMuonEfficiency*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GMuonEfficiency::Streamer(TBuffer &R__b)
{
   // Stream an object of class GMuonEfficiency.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void GMuonEfficiency::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class GMuonEfficiency.
      TClass *R__cl = ::GMuonEfficiency::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fOK", &fOK);
      R__insp.Inspect(R__cl, R__parent, "*fFile", &fFile);
      R__insp.Inspect(R__cl, R__parent, "*fTIGHTFile", &fTIGHTFile);
      R__insp.Inspect(R__cl, R__parent, "fNBins_BREMAT", &fNBins_BREMAT);
      R__insp.Inspect(R__cl, R__parent, "*fBins_BREMAT", &fBins_BREMAT);
      R__insp.Inspect(R__cl, R__parent, "*fBins_Data_BREMAT", &fBins_Data_BREMAT);
      R__insp.Inspect(R__cl, R__parent, "*fBins_MC_BREMAT", &fBins_MC_BREMAT);
      R__insp.Inspect(R__cl, R__parent, "fNBins_MPMATCH", &fNBins_MPMATCH);
      R__insp.Inspect(R__cl, R__parent, "*fBins_MPMATCH", &fBins_MPMATCH);
      R__insp.Inspect(R__cl, R__parent, "*fBins_Data_MPMATCH", &fBins_Data_MPMATCH);
      R__insp.Inspect(R__cl, R__parent, "*fBins_MC_MPMATCH", &fBins_MC_MPMATCH);
      R__insp.Inspect(R__cl, R__parent, "fNBins_MUBAC", &fNBins_MUBAC);
      R__insp.Inspect(R__cl, R__parent, "*fBins_MUBAC", &fBins_MUBAC);
      R__insp.Inspect(R__cl, R__parent, "*fBins_Data_MUBAC", &fBins_Data_MUBAC);
      R__insp.Inspect(R__cl, R__parent, "*fBins_MC_MUBAC", &fBins_MC_MUBAC);
      R__insp.Inspect(R__cl, R__parent, "fNBins_TIGHT_BREMAT", &fNBins_TIGHT_BREMAT);
      R__insp.Inspect(R__cl, R__parent, "*fBins_TIGHT_BREMAT", &fBins_TIGHT_BREMAT);
      R__insp.Inspect(R__cl, R__parent, "*fBins_TIGHT_Data_BREMAT", &fBins_TIGHT_Data_BREMAT);
      R__insp.Inspect(R__cl, R__parent, "*fBins_TIGHT_MC_BREMAT", &fBins_TIGHT_MC_BREMAT);
      R__insp.Inspect(R__cl, R__parent, "fNBins_TIGHT_MPMATCH", &fNBins_TIGHT_MPMATCH);
      R__insp.Inspect(R__cl, R__parent, "*fBins_TIGHT_MPMATCH", &fBins_TIGHT_MPMATCH);
      R__insp.Inspect(R__cl, R__parent, "*fBins_TIGHT_Data_MPMATCH", &fBins_TIGHT_Data_MPMATCH);
      R__insp.Inspect(R__cl, R__parent, "*fBins_TIGHT_MC_MPMATCH", &fBins_TIGHT_MC_MPMATCH);
      R__insp.Inspect(R__cl, R__parent, "fNBins_TIGHT_MUBAC", &fNBins_TIGHT_MUBAC);
      R__insp.Inspect(R__cl, R__parent, "*fBins_TIGHT_MUBAC", &fBins_TIGHT_MUBAC);
      R__insp.Inspect(R__cl, R__parent, "*fBins_TIGHT_Data_MUBAC", &fBins_TIGHT_Data_MUBAC);
      R__insp.Inspect(R__cl, R__parent, "*fBins_TIGHT_MC_MUBAC", &fBins_TIGHT_MC_MUBAC);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_GMuonEfficiency(void *p) {
      return  p ? new(p) ::GMuonEfficiency : new ::GMuonEfficiency;
   }
   static void *newArray_GMuonEfficiency(Long_t nElements, void *p) {
      return p ? new(p) ::GMuonEfficiency[nElements] : new ::GMuonEfficiency[nElements];
   }
   // Wrapper around operator delete
   static void delete_GMuonEfficiency(void *p) {
      delete ((::GMuonEfficiency*)p);
   }
   static void deleteArray_GMuonEfficiency(void *p) {
      delete [] ((::GMuonEfficiency*)p);
   }
   static void destruct_GMuonEfficiency(void *p) {
      typedef ::GMuonEfficiency current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GMuonEfficiency

/********************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GMuonEfficiencyDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGMuonEfficiencyDict();

extern "C" void G__set_cpp_environmentGMuonEfficiencyDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GMuonEfficiency.h");
  G__cpp_reset_tagtableGMuonEfficiencyDict();
}
#include <new>
extern "C" int G__cpp_dllrevGMuonEfficiencyDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GMuonEfficiency */
static int G__GMuonEfficiencyDict_157_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GMuonEfficiency* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GMuonEfficiency[n];
     } else {
       p = new((void*) gvp) GMuonEfficiency[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GMuonEfficiency;
     } else {
       p = new((void*) gvp) GMuonEfficiency;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_GMuonEfficiency));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GMuonEfficiency*) G__getstructoffset())->ReadinHistograms());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeight((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightForward((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightForwardMPMATCHandMUBAC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightForwardMPMATCHandNotMUBAC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightForwardNotMPMATCHandMUBAC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightBarrel((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightBarrelBREMATandMUBAC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightBarrelBREMATandNotMUBAC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightBarrelNotBREMATandMUBAC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightRear((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightRearBREMATandMUBAC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightRearBREMATandNotMUBAC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetWeightRearNotBREMATandMUBAC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseForwardEfficiencyMPMATCHData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseForwardEfficiencyMPMATCHMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseForwardEfficiencyMUBACData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseForwardEfficiencyMUBACMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseBarrelEfficiencyBREMATData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseBarrelEfficiencyBREMATMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseBarrelEfficiencyMUBACData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseBarrelEfficiencyMUBACMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseRearEfficiencyBREMATData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseRearEfficiencyBREMATMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseRearEfficiencyMUBACData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetLooseRearEfficiencyMUBACMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightForwardEfficiencyMPMATCHData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightForwardEfficiencyMPMATCHMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightForwardEfficiencyMUBACData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightForwardEfficiencyMUBACMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightBarrelEfficiencyBREMATData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightBarrelEfficiencyBREMATMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightBarrelEfficiencyMUBACData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightBarrelEfficiencyMUBACMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightRearEfficiencyBREMATData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightRearEfficiencyBREMATMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightRearEfficiencyMUBACData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetTightRearEfficiencyMUBACMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((GMuonEfficiency*) G__getstructoffset())->PrintEfficiencyInfo((GMuon*) G__int(libp->para[0]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GMuonEfficiency*) G__getstructoffset())->IsOK());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetForwardEfficiencyMPMATCHData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetForwardEfficiencyMPMATCHMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetForwardEfficiencyMUBACData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetForwardEfficiencyMUBACMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetBarrelEfficiencyBREMATData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetBarrelEfficiencyBREMATMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetBarrelEfficiencyMUBACData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetBarrelEfficiencyMUBACMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetRearEfficiencyBREMATData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetRearEfficiencyBREMATMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetRearEfficiencyMUBACData((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GMuonEfficiency*) G__getstructoffset())->GetRearEfficiencyMUBACMC((GMuon*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GMuonEfficiency::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GMuonEfficiency::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GMuonEfficiency::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GMuonEfficiency::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GMuonEfficiency*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GMuonEfficiency::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GMuonEfficiency::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GMuonEfficiency::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GMuonEfficiencyDict_157_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GMuonEfficiency::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GMuonEfficiencyDict_157_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GMuonEfficiency* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GMuonEfficiency(*(GMuonEfficiency*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_GMuonEfficiency));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GMuonEfficiency G__TGMuonEfficiency;
static int G__GMuonEfficiencyDict_157_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GMuonEfficiency*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GMuonEfficiency*) (soff+(sizeof(GMuonEfficiency)*i)))->~G__TGMuonEfficiency();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GMuonEfficiency*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GMuonEfficiency*) (soff))->~G__TGMuonEfficiency();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GMuonEfficiencyDict_157_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GMuonEfficiency* dest = (GMuonEfficiency*) G__getstructoffset();
   *dest = *(GMuonEfficiency*) libp->para[0].ref;
   const GMuonEfficiency& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GMuonEfficiency */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGMuonEfficiencyDict {
 public:
  G__Sizep2memfuncGMuonEfficiencyDict(): p(&G__Sizep2memfuncGMuonEfficiencyDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGMuonEfficiencyDict::*p)();
};

size_t G__get_sizep2memfuncGMuonEfficiencyDict()
{
  G__Sizep2memfuncGMuonEfficiencyDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGMuonEfficiencyDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_GMuonEfficiency))) {
     GMuonEfficiency *G__Lderived;
     G__Lderived=(GMuonEfficiency*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_GMuonEfficiency),G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGMuonEfficiencyDict() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GMuonEfficiency */
static void G__setup_memvarGMuonEfficiency(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_GMuonEfficiency));
   { GMuonEfficiency *p; p=(GMuonEfficiency*)0x1000; if (p) { }
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fOK=",0,"ok flag for initialization");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TFile),-1,-1,4,"fFile=",0,"muon efficiency histogram file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TFile),-1,-1,4,"fTIGHTFile=",0,"muon efficiency histogram file");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNBins_BREMAT=",0,"number of pt bins for BREMAT (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"fBins_BREMAT=",0,"pt bins for BREMAT (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_Data_BREMAT=",0,"histograms with eta histograms in pt bins for BREMAT (Data) (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_MC_BREMAT=",0,"histograms with eta histograms in pt bins for BREMAT (MC) (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNBins_MPMATCH=",0,"number of pt bins for MPMATCH (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"fBins_MPMATCH=",0,"pt bins for MPMATCH (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_Data_MPMATCH=",0,"histograms with eta histograms in pt bins for MPMATCH (Data) (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_MC_MPMATCH=",0,"histograms with eta histograms in pt bins for MPMATCH (MC) (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNBins_MUBAC=",0,"number of pt bins for MUBAC (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"fBins_MUBAC=",0,"pt bins for MUBAC (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_Data_MUBAC=",0,"histograms with eta histograms in pt bins for MUBAC (Data) (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_MC_MUBAC=",0,"histograms with eta histograms in pt bins for MUBAC (MC) (loose configuration corresponds to standard)");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNBins_TIGHT_BREMAT=",0,"number of pt bins for BREMAT (tight configuration)");
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"fBins_TIGHT_BREMAT=",0,"pt bins for BREMAT (tight configuration)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_TIGHT_Data_BREMAT=",0,"histograms with eta histograms in pt bins for BREMAT (Data) (tight configuration)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_TIGHT_MC_BREMAT=",0,"histograms with eta histograms in pt bins for BREMAT (MC) (tight configuration)");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNBins_TIGHT_MPMATCH=",0,"number of pt bins for MPMATCH (tight configuration)");
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"fBins_TIGHT_MPMATCH=",0,"pt bins for MPMATCH (tight configuration)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_TIGHT_Data_MPMATCH=",0,"histograms with eta histograms in pt bins for MPMATCH (Data) (tight configuration)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_TIGHT_MC_MPMATCH=",0,"histograms with eta histograms in pt bins for MPMATCH (MC) (tight configuration)");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNBins_TIGHT_MUBAC=",0,"number of pt bins for MUBAC (tight configuration)");
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"fBins_TIGHT_MUBAC=",0,"pt bins for MUBAC (tight configuration)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_TIGHT_Data_MUBAC=",0,"histograms with eta histograms in pt bins for MUBAC (Data) (tight configuration)");
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TH1D),-1,-1,4,"fBins_TIGHT_MC_MUBAC=",0,"histograms with eta histograms in pt bins for MUBAC (MC) (tight configuration)");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGMuonEfficiencyDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGMuonEfficiency(void) {
   /* GMuonEfficiency */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_GMuonEfficiency));
   G__memfunc_setup("GMuonEfficiency",1499,G__GMuonEfficiencyDict_157_0_1, 105, G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_GMuonEfficiency), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadinHistograms",1652,G__GMuonEfficiencyDict_157_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeight",904,G__GMuonEfficiencyDict_157_0_3, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightForward",1629,G__GMuonEfficiencyDict_157_0_4, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightForwardMPMATCHandMUBAC",2818,G__GMuonEfficiencyDict_157_0_5, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightForwardMPMATCHandNotMUBAC",3123,G__GMuonEfficiencyDict_157_0_6, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightForwardNotMPMATCHandMUBAC",3123,G__GMuonEfficiencyDict_157_0_7, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightBarrel",1504,G__GMuonEfficiencyDict_157_0_8, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightBarrelBREMATandMUBAC",2614,G__GMuonEfficiencyDict_157_0_9, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightBarrelBREMATandNotMUBAC",2919,G__GMuonEfficiencyDict_157_0_10, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightBarrelNotBREMATandMUBAC",2919,G__GMuonEfficiencyDict_157_0_11, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightRear",1298,G__GMuonEfficiencyDict_157_0_12, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightRearBREMATandMUBAC",2408,G__GMuonEfficiencyDict_157_0_13, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightRearBREMATandNotMUBAC",2713,G__GMuonEfficiencyDict_157_0_14, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetWeightRearNotBREMATandMUBAC",2713,G__GMuonEfficiencyDict_157_0_15, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseForwardEfficiencyMPMATCHData",3440,G__GMuonEfficiencyDict_157_0_16, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseForwardEfficiencyMPMATCHMC",3206,G__GMuonEfficiencyDict_157_0_17, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseForwardEfficiencyMUBACData",3278,G__GMuonEfficiencyDict_157_0_18, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseForwardEfficiencyMUBACMC",3044,G__GMuonEfficiencyDict_157_0_19, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseBarrelEfficiencyBREMATData",3236,G__GMuonEfficiencyDict_157_0_20, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseBarrelEfficiencyBREMATMC",3002,G__GMuonEfficiencyDict_157_0_21, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseBarrelEfficiencyMUBACData",3153,G__GMuonEfficiencyDict_157_0_22, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseBarrelEfficiencyMUBACMC",2919,G__GMuonEfficiencyDict_157_0_23, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseRearEfficiencyBREMATData",3030,G__GMuonEfficiencyDict_157_0_24, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseRearEfficiencyBREMATMC",2796,G__GMuonEfficiencyDict_157_0_25, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseRearEfficiencyMUBACData",2947,G__GMuonEfficiencyDict_157_0_26, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLooseRearEfficiencyMUBACMC",2713,G__GMuonEfficiencyDict_157_0_27, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightForwardEfficiencyMPMATCHData",3438,G__GMuonEfficiencyDict_157_0_28, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightForwardEfficiencyMPMATCHMC",3204,G__GMuonEfficiencyDict_157_0_29, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightForwardEfficiencyMUBACData",3276,G__GMuonEfficiencyDict_157_0_30, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightForwardEfficiencyMUBACMC",3042,G__GMuonEfficiencyDict_157_0_31, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightBarrelEfficiencyBREMATData",3234,G__GMuonEfficiencyDict_157_0_32, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightBarrelEfficiencyBREMATMC",3000,G__GMuonEfficiencyDict_157_0_33, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightBarrelEfficiencyMUBACData",3151,G__GMuonEfficiencyDict_157_0_34, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightBarrelEfficiencyMUBACMC",2917,G__GMuonEfficiencyDict_157_0_35, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightRearEfficiencyBREMATData",3028,G__GMuonEfficiencyDict_157_0_36, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightRearEfficiencyBREMATMC",2794,G__GMuonEfficiencyDict_157_0_37, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightRearEfficiencyMUBACData",2945,G__GMuonEfficiencyDict_157_0_38, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTightRearEfficiencyMUBACMC",2711,G__GMuonEfficiencyDict_157_0_39, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrintEfficiencyInfo",1934,G__GMuonEfficiencyDict_157_0_40, 117, G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TString), -1, 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsOK",342,G__GMuonEfficiencyDict_157_0_41, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetForwardEfficiencyMPMATCHData",2926,G__GMuonEfficiencyDict_157_0_42, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetForwardEfficiencyMPMATCHMC",2692,G__GMuonEfficiencyDict_157_0_43, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetForwardEfficiencyMUBACData",2764,G__GMuonEfficiencyDict_157_0_44, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetForwardEfficiencyMUBACMC",2530,G__GMuonEfficiencyDict_157_0_45, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBarrelEfficiencyBREMATData",2722,G__GMuonEfficiencyDict_157_0_46, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBarrelEfficiencyBREMATMC",2488,G__GMuonEfficiencyDict_157_0_47, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBarrelEfficiencyMUBACData",2639,G__GMuonEfficiencyDict_157_0_48, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBarrelEfficiencyMUBACMC",2405,G__GMuonEfficiencyDict_157_0_49, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetRearEfficiencyBREMATData",2516,G__GMuonEfficiencyDict_157_0_50, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetRearEfficiencyBREMATMC",2282,G__GMuonEfficiencyDict_157_0_51, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetRearEfficiencyMUBACData",2433,G__GMuonEfficiencyDict_157_0_52, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetRearEfficiencyMUBACMC",2199,G__GMuonEfficiencyDict_157_0_53, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'GMuon' - 0 - muon", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__GMuonEfficiencyDict_157_0_54, 85, G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GMuonEfficiency::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GMuonEfficiencyDict_157_0_55, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GMuonEfficiency::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GMuonEfficiencyDict_157_0_56, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GMuonEfficiency::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GMuonEfficiencyDict_157_0_57, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GMuonEfficiency::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GMuonEfficiencyDict_157_0_61, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GMuonEfficiencyDict_157_0_62, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GMuonEfficiency::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GMuonEfficiencyDict_157_0_63, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GMuonEfficiency::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GMuonEfficiencyDict_157_0_64, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GMuonEfficiency::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GMuonEfficiencyDict_157_0_65, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GMuonEfficiency::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GMuonEfficiency", 1499, G__GMuonEfficiencyDict_157_0_66, (int) ('i'), G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_GMuonEfficiency), -1, 0, 1, 1, 1, 0, "u 'GMuonEfficiency' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GMuonEfficiency", 1625, G__GMuonEfficiencyDict_157_0_67, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GMuonEfficiencyDict_157_0_68, (int) ('u'), G__get_linked_tagnum(&G__GMuonEfficiencyDictLN_GMuonEfficiency), -1, 1, 1, 1, 1, 0, "u 'GMuonEfficiency' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGMuonEfficiencyDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGMuonEfficiencyDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGMuonEfficiencyDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GMuonEfficiencyDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_GMuon = { "GMuon" , 99 , -1 };
G__linked_taginfo G__GMuonEfficiencyDictLN_GMuonEfficiency = { "GMuonEfficiency" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGMuonEfficiencyDict() {
  G__GMuonEfficiencyDictLN_TClass.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_TBuffer.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_TMemberInspector.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_TObject.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_TString.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_TH1D.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_TFile.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_GMuon.tagnum = -1 ;
  G__GMuonEfficiencyDictLN_GMuonEfficiency.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGMuonEfficiencyDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_TString);
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_GMuon);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GMuonEfficiencyDictLN_GMuonEfficiency),sizeof(GMuonEfficiency),-1,29952,"muon efficiency class",G__setup_memvarGMuonEfficiency,G__setup_memfuncGMuonEfficiency);
}
extern "C" void G__cpp_setupGMuonEfficiencyDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGMuonEfficiencyDict()");
  G__set_cpp_environmentGMuonEfficiencyDict();
  G__cpp_setup_tagtableGMuonEfficiencyDict();

  G__cpp_setup_inheritanceGMuonEfficiencyDict();

  G__cpp_setup_typetableGMuonEfficiencyDict();

  G__cpp_setup_memvarGMuonEfficiencyDict();

  G__cpp_setup_memfuncGMuonEfficiencyDict();
  G__cpp_setup_globalGMuonEfficiencyDict();
  G__cpp_setup_funcGMuonEfficiencyDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGMuonEfficiencyDict();
  return;
}
class G__cpp_setup_initGMuonEfficiencyDict {
  public:
    G__cpp_setup_initGMuonEfficiencyDict() { G__add_setup_func("GMuonEfficiencyDict",(G__incsetup)(&G__cpp_setupGMuonEfficiencyDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGMuonEfficiencyDict() { G__remove_setup_func("GMuonEfficiencyDict"); }
};
G__cpp_setup_initGMuonEfficiencyDict G__cpp_setup_initializerGMuonEfficiencyDict;

