//
// File generated by rootcint at Thu Oct 23 10:41:38 2014

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GTJMatchDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GTJMatch_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_GTJMatch(void *p);
   static void deleteArray_GTJMatch(void *p);
   static void destruct_GTJMatch(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GTJMatch*)
   {
      ::GTJMatch *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GTJMatch >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GTJMatch", ::GTJMatch::Class_Version(), "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GTJMatch.h", 28,
                  typeid(::GTJMatch), DefineBehavior(ptr, ptr),
                  &::GTJMatch::Dictionary, isa_proxy, 0,
                  sizeof(::GTJMatch) );
      instance.SetDelete(&delete_GTJMatch);
      instance.SetDeleteArray(&deleteArray_GTJMatch);
      instance.SetDestructor(&destruct_GTJMatch);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GTJMatch*)
   {
      return GenerateInitInstanceLocal((::GTJMatch*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GTJMatch*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GTJMatch::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GTJMatch::Class_Name()
{
   return "GTJMatch";
}

//______________________________________________________________________________
const char *GTJMatch::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GTJMatch*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GTJMatch::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GTJMatch*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GTJMatch::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GTJMatch*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GTJMatch::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GTJMatch*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GTJMatch::Streamer(TBuffer &R__b)
{
   // Stream an object of class GTJMatch.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void GTJMatch::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class GTJMatch.
      TClass *R__cl = ::GTJMatch::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fType", &fType);
      R__insp.Inspect(R__cl, R__parent, "*fJet", &fJet);
      R__insp.Inspect(R__cl, R__parent, "*fTrack", &fTrack);
      R__insp.Inspect(R__cl, R__parent, "fDeltaR", &fDeltaR);
      R__insp.Inspect(R__cl, R__parent, "fDeltaPhi", &fDeltaPhi);
      R__insp.Inspect(R__cl, R__parent, "fDeltaEta", &fDeltaEta);
      R__insp.Inspect(R__cl, R__parent, "fDeltaTheta", &fDeltaTheta);
      R__insp.Inspect(R__cl, R__parent, "fPtRel", &fPtRel);
      R__insp.Inspect(R__cl, R__parent, "fPtRelJetMinTrack", &fPtRelJetMinTrack);
      R__insp.Inspect(R__cl, R__parent, "fTrackMinusJetPt", &fTrackMinusJetPt);
      R__insp.Inspect(R__cl, R__parent, "fTJCosThetaStar", &fTJCosThetaStar);
      R__insp.Inspect(R__cl, R__parent, "fTJCosThetaStarSecJetID", &fTJCosThetaStarSecJetID);
      R__insp.Inspect(R__cl, R__parent, "fTJCosThetaStarXgamma", &fTJCosThetaStarXgamma);
      R__insp.Inspect(R__cl, R__parent, "fTrackAllCuts", &fTrackAllCuts);
      R__insp.Inspect(R__cl, R__parent, "fTrackMuonKinCuts", &fTrackMuonKinCuts);
      R__insp.Inspect(R__cl, R__parent, "fJetCritCuts", &fJetCritCuts);
      R__insp.Inspect(R__cl, R__parent, "fJetPtCut", &fJetPtCut);
      R__insp.Inspect(R__cl, R__parent, "fTrackMinusJetPtCut", &fTrackMinusJetPtCut);
      R__insp.Inspect(R__cl, R__parent, "fAllCuts", &fAllCuts);
      R__insp.Inspect(R__cl, R__parent, "fTJCosThetaStar_EtaJets", &fTJCosThetaStar_EtaJets);
      R__insp.Inspect(R__cl, R__parent, "fTJCosThetaStar_MJets", &fTJCosThetaStar_MJets);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_GTJMatch(void *p) {
      delete ((::GTJMatch*)p);
   }
   static void deleteArray_GTJMatch(void *p) {
      delete [] ((::GTJMatch*)p);
   }
   static void destruct_GTJMatch(void *p) {
      typedef ::GTJMatch current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GTJMatch

/********************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GTJMatchDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGTJMatchDict();

extern "C" void G__set_cpp_environmentGTJMatchDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GTJMatch.h");
  G__cpp_reset_tagtableGTJMatchDict();
}
#include <new>
extern "C" int G__cpp_dllrevGTJMatchDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GTJMatch */
static int G__GTJMatchDict_157_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GTJMatch* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new GTJMatch((GTrack*) G__int(libp->para[0]), (GJet*) G__int(libp->para[1]));
   } else {
     p = new((void*) gvp) GTJMatch((GTrack*) G__int(libp->para[0]), (GJet*) G__int(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GTJMatchDictLN_GTJMatch));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GTJMatch*) G__getstructoffset())->Calculate());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((GTJMatch*) G__getstructoffset())->GetJet());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((GTJMatch*) G__getstructoffset())->GetTrack());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetDeltaR());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetDeltaPhi());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetDeltaEta());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetDeltaTheta());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetPtRel());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetPtRelJetMinTrack());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetTrackMinusJetPt());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetTrackAllCuts((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetJetCritCuts((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetJetPtCut((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetTrackMuonKinCuts((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetTrackMinusJetPtCut((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetAllCuts((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetType((EZTJMatchType) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetTJCosThetaStar((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetSecondJetID((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetTJCosThetaStar_xgamma((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetTJCosThetaStar_EtaJets((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->SetTJCosThetaStar_MJets((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetTJCosThetaStar());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GTJMatch*) G__getstructoffset())->GetSecondJetID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetTJCosThetaStar_xgamma());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetTJCosThetaStar_MJets());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GTJMatch*) G__getstructoffset())->GetTJCosThetaStar_EtaJets());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GTJMatch*) G__getstructoffset())->GetTrackAllCuts());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GTJMatch*) G__getstructoffset())->GetJetCritCuts());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GTJMatch*) G__getstructoffset())->GetJetPtCut());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GTJMatch*) G__getstructoffset())->GetTrackMuonKinCuts());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GTJMatch*) G__getstructoffset())->GetTrackMinusJetPtCut());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GTJMatch*) G__getstructoffset())->GetAllCuts());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GTJMatch*) G__getstructoffset())->GetType());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((GTJMatch*) G__getstructoffset())->PrintMessage(*((TString*) G__int(libp->para[0])));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GTJMatch*) G__getstructoffset())->Print(*((TString*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GTJMatch::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GTJMatch::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GTJMatch::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GTJMatch::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GTJMatch*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GTJMatch::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GTJMatch::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GTJMatch::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GTJMatchDict_157_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GTJMatch::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GTJMatchDict_157_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GTJMatch* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GTJMatch(*(GTJMatch*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GTJMatchDictLN_GTJMatch));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GTJMatch G__TGTJMatch;
static int G__GTJMatchDict_157_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GTJMatch*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GTJMatch*) (soff+(sizeof(GTJMatch)*i)))->~G__TGTJMatch();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GTJMatch*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GTJMatch*) (soff))->~G__TGTJMatch();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GTJMatchDict_157_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GTJMatch* dest = (GTJMatch*) G__getstructoffset();
   *dest = *(GTJMatch*) libp->para[0].ref;
   const GTJMatch& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GTJMatch */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGTJMatchDict {
 public:
  G__Sizep2memfuncGTJMatchDict(): p(&G__Sizep2memfuncGTJMatchDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGTJMatchDict::*p)();
};

size_t G__get_sizep2memfuncGTJMatchDict()
{
  G__Sizep2memfuncGTJMatchDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGTJMatchDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GTJMatchDictLN_GTJMatch))) {
     GTJMatch *G__Lderived;
     G__Lderived=(GTJMatch*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GTJMatchDictLN_GTJMatch),G__get_linked_tagnum(&G__GTJMatchDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGTJMatchDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__GTJMatchDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GTJMatchDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GTJMatchDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GTJMatchDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GTJMatchDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GTJMatchDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GTJMatch */
static void G__setup_memvarGTJMatch(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GTJMatchDictLN_GTJMatch));
   { GTJMatch *p; p=(GTJMatch*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__GTJMatchDictLN_EZTJMatchType),-1,-1,4,"fType=",0,"type of jet-track match");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GTJMatchDictLN_GJet),-1,-1,4,"fJet=",0,"pointer to jet belonging to this match");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GTJMatchDictLN_GTrack),-1,-1,4,"fTrack=",0,"pointer to track belonging to this match");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fDeltaR=",0,"discriminant delta r = sqrt(delta-eta^2+delta-phi^2)");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fDeltaPhi=",0,"difference in phi between jet and muon (always positive)");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fDeltaEta=",0,"difference in eta between jet and muon (always positive)");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fDeltaTheta=",0,"difference in theta between jet and muon (always positive)");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fPtRel=",0,"relative transverse momentum of track to jet");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fPtRelJetMinTrack=",0,"relative transverse momentum of track to (jet-track)");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fTrackMinusJetPt=",0,"track - jet p_t");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fTJCosThetaStar=",0,"costhetastar for TJMatched jets");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fTJCosThetaStarSecJetID=",0,"id of second jet for calculation ");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fTJCosThetaStarXgamma=",0,"xgamma calculated from these jets");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fTrackAllCuts=",0,"track of match fulfills all cuts");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fTrackMuonKinCuts=",0,"track fulfills muon kinematics cuts");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fJetCritCuts=",0,"event fulfills jet criteria cuts");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fJetPtCut=",0,"jet of muon fulfills p_t cut");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fTrackMinusJetPtCut=",0,"match fulfills cut on p_t of track-jet");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fAllCuts=",0,"match fulfills all cuts");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fTJCosThetaStar_EtaJets=",0,"average eta from jets in costhetastar calculation");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fTJCosThetaStar_MJets=",0,"mass of jets in costhetastar calculation");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GTJMatchDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGTJMatchDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGTJMatch(void) {
   /* GTJMatch */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GTJMatchDictLN_GTJMatch));
   G__memfunc_setup("GTJMatch",722,G__GTJMatchDict_157_0_1, 105, G__get_linked_tagnum(&G__GTJMatchDictLN_GTJMatch), -1, 0, 2, 1, 1, 0, 
"U 'GTrack' - 0 - track U 'GJet' - 0 - jet", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Calculate",910,G__GTJMatchDict_157_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetJet",579,G__GTJMatchDict_157_0_3, 85, G__get_linked_tagnum(&G__GTJMatchDictLN_GJet), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTrack",789,G__GTJMatchDict_157_0_4, 85, G__get_linked_tagnum(&G__GTJMatchDictLN_GTrack), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDeltaR",860,G__GTJMatchDict_157_0_5, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDeltaPhi",1067,G__GTJMatchDict_157_0_6, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDeltaEta",1060,G__GTJMatchDict_157_0_7, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDeltaTheta",1280,G__GTJMatchDict_157_0_8, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPtRel",775,G__GTJMatchDict_157_0_9, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPtRelJetMinTrack",1859,G__GTJMatchDict_157_0_10, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTrackMinusJetPt",1800,G__GTJMatchDict_157_0_11, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTrackAllCuts",1497,G__GTJMatchDict_157_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetJetCritCuts",1408,G__GTJMatchDict_157_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetJetPtCut",1087,G__GTJMatchDict_157_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTrackMuonKinCuts",1921,G__GTJMatchDict_157_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTrackMinusJetPtCut",2112,G__GTJMatchDict_157_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetAllCuts",996,G__GTJMatchDict_157_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetType",718,G__GTJMatchDict_157_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "i 'EZTJMatchType' - 0 - type", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTJCosThetaStar",1663,G__GTJMatchDict_157_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetSecondJetID",1336,G__GTJMatchDict_157_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTJCosThetaStar_xgamma",2393,G__GTJMatchDict_157_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTJCosThetaStar_EtaJets",2446,G__GTJMatchDict_157_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTJCosThetaStar_MJets",2241,G__GTJMatchDict_157_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTJCosThetaStar",1651,G__GTJMatchDict_157_0_24, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetSecondJetID",1324,G__GTJMatchDict_157_0_25, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTJCosThetaStar_xgamma",2381,G__GTJMatchDict_157_0_26, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTJCosThetaStar_MJets",2229,G__GTJMatchDict_157_0_27, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTJCosThetaStar_EtaJets",2434,G__GTJMatchDict_157_0_28, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTrackAllCuts",1485,G__GTJMatchDict_157_0_29, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetJetCritCuts",1396,G__GTJMatchDict_157_0_30, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetJetPtCut",1075,G__GTJMatchDict_157_0_31, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTrackMuonKinCuts",1909,G__GTJMatchDict_157_0_32, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTrackMinusJetPtCut",2100,G__GTJMatchDict_157_0_33, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetAllCuts",984,G__GTJMatchDict_157_0_34, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetType",706,G__GTJMatchDict_157_0_35, 105, G__get_linked_tagnum(&G__GTJMatchDictLN_EZTJMatchType), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrintMessage",1234,G__GTJMatchDict_157_0_36, 117, G__get_linked_tagnum(&G__GTJMatchDictLN_TString), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Print",525,G__GTJMatchDict_157_0_37, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "u 'TString' - 0 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__GTJMatchDict_157_0_38, 85, G__get_linked_tagnum(&G__GTJMatchDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GTJMatch::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GTJMatchDict_157_0_39, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GTJMatch::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GTJMatchDict_157_0_40, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GTJMatch::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GTJMatchDict_157_0_41, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GTJMatch::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GTJMatchDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GTJMatchDict_157_0_45, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GTJMatchDict_157_0_46, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GTJMatch::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GTJMatchDict_157_0_47, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GTJMatch::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GTJMatchDict_157_0_48, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GTJMatch::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GTJMatchDict_157_0_49, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GTJMatch::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GTJMatch", 722, G__GTJMatchDict_157_0_50, (int) ('i'), G__get_linked_tagnum(&G__GTJMatchDictLN_GTJMatch), -1, 0, 1, 1, 1, 0, "u 'GTJMatch' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GTJMatch", 848, G__GTJMatchDict_157_0_51, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GTJMatchDict_157_0_52, (int) ('u'), G__get_linked_tagnum(&G__GTJMatchDictLN_GTJMatch), -1, 1, 1, 1, 1, 0, "u 'GTJMatch' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGTJMatchDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGTJMatchDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGTJMatchDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GTJMatchDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GTJMatchDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GTJMatchDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GTJMatchDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GTJMatchDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GTJMatchDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GTJMatchDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__GTJMatchDictLN_GJet = { "GJet" , 99 , -1 };
G__linked_taginfo G__GTJMatchDictLN_GTrack = { "GTrack" , 99 , -1 };
G__linked_taginfo G__GTJMatchDictLN_EZTJMatchType = { "EZTJMatchType" , 101 , -1 };
G__linked_taginfo G__GTJMatchDictLN_GTJMatch = { "GTJMatch" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGTJMatchDict() {
  G__GTJMatchDictLN_TClass.tagnum = -1 ;
  G__GTJMatchDictLN_TBuffer.tagnum = -1 ;
  G__GTJMatchDictLN_TMemberInspector.tagnum = -1 ;
  G__GTJMatchDictLN_TObject.tagnum = -1 ;
  G__GTJMatchDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GTJMatchDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GTJMatchDictLN_TString.tagnum = -1 ;
  G__GTJMatchDictLN_GJet.tagnum = -1 ;
  G__GTJMatchDictLN_GTrack.tagnum = -1 ;
  G__GTJMatchDictLN_EZTJMatchType.tagnum = -1 ;
  G__GTJMatchDictLN_GTJMatch.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGTJMatchDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_TString);
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_GJet);
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_GTrack);
   G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_EZTJMatchType);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GTJMatchDictLN_GTJMatch),sizeof(GTJMatch),-1,62464,"track-jet match class",G__setup_memvarGTJMatch,G__setup_memfuncGTJMatch);
}
extern "C" void G__cpp_setupGTJMatchDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGTJMatchDict()");
  G__set_cpp_environmentGTJMatchDict();
  G__cpp_setup_tagtableGTJMatchDict();

  G__cpp_setup_inheritanceGTJMatchDict();

  G__cpp_setup_typetableGTJMatchDict();

  G__cpp_setup_memvarGTJMatchDict();

  G__cpp_setup_memfuncGTJMatchDict();
  G__cpp_setup_globalGTJMatchDict();
  G__cpp_setup_funcGTJMatchDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGTJMatchDict();
  return;
}
class G__cpp_setup_initGTJMatchDict {
  public:
    G__cpp_setup_initGTJMatchDict() { G__add_setup_func("GTJMatchDict",(G__incsetup)(&G__cpp_setupGTJMatchDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGTJMatchDict() { G__remove_setup_func("GTJMatchDict"); }
};
G__cpp_setup_initGTJMatchDict G__cpp_setup_initializerGTJMatchDict;

