/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GTJMatchsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GTJMatchsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGTJMatchsDict();
extern void G__cpp_setup_inheritanceGTJMatchsDict();
extern void G__cpp_setup_typetableGTJMatchsDict();
extern void G__cpp_setup_memvarGTJMatchsDict();
extern void G__cpp_setup_globalGTJMatchsDict();
extern void G__cpp_setup_memfuncGTJMatchsDict();
extern void G__cpp_setup_funcGTJMatchsDict();
extern void G__set_cpp_environmentGTJMatchsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GTJMatchs.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GTJMatchsDictLN_TClass;
extern G__linked_taginfo G__GTJMatchsDictLN_TBuffer;
extern G__linked_taginfo G__GTJMatchsDictLN_TMemberInspector;
extern G__linked_taginfo G__GTJMatchsDictLN_TObject;
extern G__linked_taginfo G__GTJMatchsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GTJMatchsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GTJMatchsDictLN_TString;
extern G__linked_taginfo G__GTJMatchsDictLN_TClonesArray;
extern G__linked_taginfo G__GTJMatchsDictLN_TH1D;
extern G__linked_taginfo G__GTJMatchsDictLN_GPhysObj;
extern G__linked_taginfo G__GTJMatchsDictLN_GTJMatch;
extern G__linked_taginfo G__GTJMatchsDictLN_GTJMatchs;

/* STUB derived class for protected member access */
