/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GTriMuonDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GTriMuonDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGTriMuonDict();
extern void G__cpp_setup_inheritanceGTriMuonDict();
extern void G__cpp_setup_typetableGTriMuonDict();
extern void G__cpp_setup_memvarGTriMuonDict();
extern void G__cpp_setup_globalGTriMuonDict();
extern void G__cpp_setup_memfuncGTriMuonDict();
extern void G__cpp_setup_funcGTriMuonDict();
extern void G__set_cpp_environmentGTriMuonDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GTriMuon.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GTriMuonDictLN_TClass;
extern G__linked_taginfo G__GTriMuonDictLN_TBuffer;
extern G__linked_taginfo G__GTriMuonDictLN_TMemberInspector;
extern G__linked_taginfo G__GTriMuonDictLN_TObject;
extern G__linked_taginfo G__GTriMuonDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GTriMuonDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GTriMuonDictLN_TString;
extern G__linked_taginfo G__GTriMuonDictLN_GMuon;
extern G__linked_taginfo G__GTriMuonDictLN_EZTriMuonType;
extern G__linked_taginfo G__GTriMuonDictLN_EZTriMuonTriggerType;
extern G__linked_taginfo G__GTriMuonDictLN_GMC;
extern G__linked_taginfo G__GTriMuonDictLN_GTriMuon;

/* STUB derived class for protected member access */
