/********************************************************************
* /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GZufoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/dict/GZufoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableGZufoDict();
extern void G__cpp_setup_inheritanceGZufoDict();
extern void G__cpp_setup_typetableGZufoDict();
extern void G__cpp_setup_memvarGZufoDict();
extern void G__cpp_setup_globalGZufoDict();
extern void G__cpp_setup_memfuncGZufoDict();
extern void G__cpp_setup_funcGZufoDict();
extern void G__set_cpp_environmentGZufoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/data/zenith234d/stefan/GoodCodeGit/libraries/GutLib/inc//GZufo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GZufoDictLN_TClass;
extern G__linked_taginfo G__GZufoDictLN_TBuffer;
extern G__linked_taginfo G__GZufoDictLN_TMemberInspector;
extern G__linked_taginfo G__GZufoDictLN_TObject;
extern G__linked_taginfo G__GZufoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GZufoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GZufoDictLN_TString;
extern G__linked_taginfo G__GZufoDictLN_TH1D;
extern G__linked_taginfo G__GZufoDictLN_TH2D;
extern G__linked_taginfo G__GZufoDictLN_GMuon;
extern G__linked_taginfo G__GZufoDictLN_GDIMuon;
extern G__linked_taginfo G__GZufoDictLN_GTriMuon;
extern G__linked_taginfo G__GZufoDictLN_GPhysObj;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GZufoDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GZufoDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__GZufoDictLN_TVector3;
extern G__linked_taginfo G__GZufoDictLN_GZufo;

/* STUB derived class for protected member access */
