#!/bin/sh
#
# copy mini-ntuples to new project
#
# input variables
#
# $1: project name (subdir in $GUTCODEDIR)
#
if [ -z $1 ]; then
    echo ""
    echo "Please give project name"
    echo ""
    echo "Usage: generate_cards [project]"
    echo ""
    exit
fi
#
for dir in 96p 97p 98e 99e 99p 00p 03p 04p 05e 06e 06p 07p
do
  if [ -f $dir/$1/smallntuple.root ]; then
    echo "Copy mini ntuple to new project $GUTDATADIR/$1/data/$dir/data/ "
    cd $dir/$1
    mkdir -p $GUTDATADIR/$1/data/$dir/data
    cp smallntuple*.root $GUTDATADIR/$1/data/$dir/data
    cd ../..
  fi
done
