#!/bin/sh
#
# execute analyses
#
# input variables
#
# $1: version of data (subdir)
# $2: path and name of merged histogram-file
# 
if [ -z $1 ]; then
    echo ""
    echo "Please give data-version, outputname of resulting root file"
    echo ""
    echo "Usage: execute [version] [outputname]"
    echo ""
    exit
fi
#
if [ -z $2 ]; then
    echo ""
    echo "Please give merged histogram-file name"
    echo ""
    echo "Usage: execute [version] [outputname]"
    echo ""
    exit
fi
#
for dir in 96p 97p 98e 99e 99p 00p 03p 04p 05e 06e 06p 07p
do
  if [ -d $dir/$1 ]; then
    echo "Analysing $dir/$1"
    cd $dir/$1
    ./execute $2
    cd ../..
  fi
done
