#!/bin/sh
#
# merge histogram-files
#
# input variables
#
# $1: version of data (subdir)
# $2: path and name of merged histogram-file
#
if [ -z $1 ]; then
    echo ""
    echo "Please give data-version"
    echo ""
    echo "Usage: merge [version] [outputname]"
    echo ""
    exit
fi
#
if [ -z $2 ]; then
    echo ""
    echo "Please give merged histogram-file"
    echo ""
    echo "Usage: merge [version] [outputname]"
    echo ""
    exit
fi
#
for dir in 96p 97p 98e 99e 99p 00p 03p 04p 05e 06e 06p 07p
do
  if [ -d $dir/$1 ]; then
    echo "Merging $dir/$1"
    cd $dir/$1
    ./merge $2
    cd ../..
  fi
done
