#!/bin/sh
#
# extract ibl histos from histogram-files
#
# input variables
#
# $1: version of data (subdir)
# $2: path and name of merged histogram-file
#
if [ -z $1 ]; then
    echo ""
    echo "Please give data-version"
    echo ""
    echo "Usage: merge [version] [outputname]"
    echo ""
    exit
fi
#
if [ -z $2 ]; then
    echo ""
    echo "Please give merged histogram-file"
    echo ""
    echo "Usage: merge [version] [outputname]"
    echo ""
    exit
fi
#
#for dir in 99p-00p 96p 97p 98e 99e 99p 00p 02p 03p 03p_7a 03p_8a 03p_9a 03p_9b 04p 05e 06e 06p 07p
for dir in 03p 04p 05e 06e 06p 07p
#for dir in 06p 07p
do
  if [ -d $dir/$1 ]; then
    echo "Extracting from $dir/$1"
    cd $dir/$1
#    root -l /home/ibloch/lap_ZEUS/macros/analysis_macros/oli_to_ingo_auto.C+
     root -l $GUTANADIR/analysis_macros/oli_to_danny.C+
    cp oli2danny_out.root $GUTANADIR/$dir.root
    cd ../..
  fi
done
