#!/bin/sh
#
# extract ibl histos from histogram-files
#
# input variables
#
# $1: version of data (subdir)
# $2: path and name of merged histogram-file
#
if [ -z $1 ]; then
    echo ""
    echo "Please give data-version"
    echo ""
    echo "Usage: merge [version] [outputname]"
    echo ""
    exit
fi
#
if [ -z $2 ]; then
    echo ""
    echo "Please give merged histogram-file"
    echo ""
    echo "Usage: merge [version] [outputname]"
    echo ""
    exit
fi
#
for dir in 05e
#
do
  if [ -d $dir/$1 ]; then
    echo "Extracting from $dir/$1"
    cd $dir/$1
#    root -l /home/ibloch/lap_ZEUS/macros/analysis_macros/oli_to_ingo_auto.C+
     root -l $GUTANADIR/analysis_macros/oli_to_danny_dimuon.C+
    cp oli2danny_out.root $GUTANADIR/$dir.root
    cd ../..
  fi
done
