#!/bin/sh

cd ../
# analyse mini_HeraII_0304p_Data_MC_Dimuon_Finalversion dbot_general_gmuon_dimuon_analyse_12_HeraII_Switch_0304p.cards
# analyse mini_HeraII_05e_Data_MC_Dimuon_Finalversion dbot_general_gmuon_dimuon_analyse_12_HeraII_Switch_05e.cards
analyse mini_HeraII_06e_Data_MC_Dimuon_Finalversion dbot_general_gmuon_dimuon_analyse_12_HeraII_Switch_06e.cards
analyse mini_HeraII_0607p_Data_MC_Dimuon_Finalversion dbot_general_gmuon_dimuon_analyse_12_HeraII_Switch_0607p.cards
