#!/bin/sh

getdanny_XsectionTotal2_0304p.sh mini_HeraII_0304p_Data_MC_Dimuon_Finalversion
getdanny_XsectionTotal2_05e.sh mini_HeraII_05e_Data_MC_Dimuon_Finalversion
getdanny_XsectionTotal2_06e.sh mini_HeraII_06e_Data_MC_Dimuon_Finalversion
getdanny_XsectionTotal2_0607p.sh mini_HeraII_0607p_Data_MC_Dimuon_Finalversion
