#!/bin/sh

getdanny_dimuon_0304p.sh mini_HeraII_0304p_Data_MC_Dimuon_Final_subsets
getdanny_dimuon_05e.sh mini_HeraII_05e_Data_MC_Dimuon_Final_subsets
getdanny_dimuon_06e.sh mini_HeraII_06e_Data_MC_Dimuon_Final_subsets
getdanny_dimuon_0607p.sh mini_HeraII_0607p_Data_MC_Dimuon_Final_subsets
