#!/bin/sh

# getdanny_secvtx_0304p.sh mini_HeraII_0304p_Data_MC_Dimuon_Finalversion
# getdanny_secvtx_05e.sh mini_HeraII_05e_Data_MC_Dimuon_Finalversion
# getdanny_secvtx_06e.sh mini_HeraII_06e_Data_MC_Dimuon_Finalversion
# getdanny_secvtx_0607p.sh mini_HeraII_0607p_Data_MC_Dimuon_Finalversion

getdanny_secvtx_0304p.sh mini_HeraII_0304p_Data_MC_Dimuon_Final_subsets
getdanny_secvtx_05e.sh mini_HeraII_05e_Data_MC_Dimuon_Final_subsets
getdanny_secvtx_06e.sh mini_HeraII_06e_Data_MC_Dimuon_Final_subsets
getdanny_secvtx_0607p.sh mini_HeraII_0607p_Data_MC_Dimuon_Final_subsets

