#!/bin/sh
#
# link new project
#
# input variables
#
# $1: versionversion of data (subdir)
# $2: date (if date is not given, date is created)
#
#
if [ -z $1 ]; then
    echo ""
    echo "Please give data-version"
    echo ""
    echo "Usage: link [version]"
    echo ""
    exit
fi
#
if [ -z $2 ]; then
    export date=`date +%y%m%d_%H%M%S`
else
    export date=$2
fi
#
for dir in 99p-00p 96p 97p 98e 99e 99p 00p 02p 03p 03p_7a 03p_8a 03p_9a 03p_9b 04p 05e
do
  if [ -d $GUTDATADIR/$1/data/$dir ]; then
    newname=`echo "$1_$date"`
    cd $dir
    cp -pr template $newname
    rm -rf $1
    ln -s $newname $1
    cd $1/data
    ln -s $GUTDATADIR/$1/data/$dir/data/*.root .
    cd ../../..
  fi
done
