#!/bin/sh
#
# copy mini-ntuples to new project
#
# input variables
#
# $1: project name (subdir in $GUTCODEDIR)
#
if [ -z $1 ]; then
    echo ""
    echo "Please give project name"
    echo ""
    echo "Usage: generate_cards [project]"
    echo ""
    exit
fi
#
for ver in 99p-00p 96p-97p
do
  for dir in all
  do
    if [ -f $ver/$dir/$1/smallntuple.root ]; then
      echo "Copy mini ntuple to new project $GUTDATADIR/mini_$1/mc/psiprime/$ver/$dir "
      cd $ver/$dir/$1
      mkdir -p $GUTDATADIR/mini_$1/mc/psiprime/$ver/$dir/data
      mv smallntuple*.root $GUTDATADIR/mini_$1/mc/psiprime/$ver/$dir/data
      cd ../../..
    fi
  done
done
