#!/bin/sh
#
# generate cards
#
# $1: cards template
#
if [ -z $1 ]; then
    echo ""
    echo "Please give cards file template"
    echo ""
    echo "Usage: generate_cards [template]"
    echo ""
    exit
fi
#
cardmaker.exe ANALUMIMCBBBARRAP data $1 2577.944 06p-07p mc_b_dirrap.cards

