#!/bin/sh
#
# execute analyses
#
# parameters
#
# $1: path and name of merged histogram-file
#
if [ -z $1 ]; then
    echo ""
    echo "Please give merged histogram-file"
    echo ""
    echo "Usage: execute [outputname]"
    echo ""
    exit
fi
#
nice -20 analysis.exe mc_jpsi_jpsi2.cards
merger.exe MERGE histos.root $1 mc/05e/jpsi/jpsi2

