#!/bin/sh
#
# link new project
#
# input variables
#
# $1: versionversion of data (subdir)
# $2: date (if date is not given, date is created)
#
#
if [ -z $1 ]; then
    echo ""
    echo "Please give data-version"
    echo ""
    echo "Usage: link [version]"
    echo ""
    exit
fi
#
if [ -z $2 ]; then
    export date=`date +%y%m%d_%H%M%S`
else
    export date=$2
fi
#
for ver in 99p-00p 98e-99e 96p-97p 03p-04p 95p
do
  for dir in jpsi1 jpsi2 jpsi3 jpsi4 jpsi5 jpsi6 jpsi7 jpsi8 jpsi9 jpsia jpsib jpsic jpsid
  do
    if [ -d $GUTDATADIR/$1/mc/jpsi/$ver/$dir ]; then
      newname=`echo "$1_$date"`
      cd $ver/$dir
      cp -pr template $newname
      rm -rf $1
      ln -s $newname $1
      cd $1/data
      ln -s $GUTDATADIR/$1/mc/jpsi/$ver/$dir/data/*.root .
      cd ../../../..
    fi
  done
done
