#!/bin/sh

ln -s /nfs/dust/zeus/group/stefan/inputdata/miniNT_from_Danny/mini_HeraII_0304p_Data_MC_Dimuon_Finalversion mini_HeraII_0304p_Data_MC_Dimuon_Finalversion
ln -s /nfs/dust/zeus/group/stefan/inputdata/miniNT_from_Danny/mini_HeraII_06e_Data_MC_Dimuon_Finalversion mini_HeraII_06e_Data_MC_Dimuon_Finalversion
ln -s /nfs/dust/zeus/group/stefan/inputdata/miniNT_from_Danny/mini_HeraII_0607p_Data_MC_Dimuon_Finalversion mini_HeraII_0607p_Data_MC_Dimuon_Finalversion
ln -s /nfs/dust/zeus/group/stefan/inputdata/miniNT_from_Danny/mini_HeraII_05e_Data_MC_Dimuon_Finalversion mini_HeraII_05e_Data_MC_Dimuon_Finalversion

ln -s /nfs/dust/zeus/group/stefan/inputdata/partical_test_miniNT/mini_HeraII_05e_Data_only_Dimuon_Finalversion mini_HeraII_05e_Data_only_Dimuon_Finalversion
