#!/bin/sh
#
# generate cards
#
# $1:  cards template
#
if [ -z $1 ]; then
    echo ""
    echo "Please give cards file template"
    echo ""
    echo "Usage: generate_cards [template]"
    echo ""
    exit
fi
#
cardmaker.exe ANALUMIMCCCBAR data $1 290.27 99p-00p mc_c_exgamma_2.cards

