#!/bin/sh
#
# generate cards
#
# $1: cards template
#
if [ -z $1 ]; then
    echo ""
    echo "Please give cards file template"
    echo ""
    echo "Usage: generate_cards [template]"
    echo ""
    exit
fi
#
cardmaker.exe ANALUMIMCCCBARRAP data $1 100.273 03p-04p mc_c_dir.cards

