#!/bin/sh
#
# copy mini-ntuples to new project
#
# input variables
#
# $1: project name (subdir in $GUTCODEDIR)
#
if [ -z $1 ]; then
    echo ""
    echo "Please give project name"
    echo ""
    echo "Usage: generate_cards [project]"
    echo ""
    exit
fi
#
for dir in b c lf jpsi psiprime upsilon bh 
do
  echo "Copy mini ntuples from $1 to new project dir"
  cd $dir
  ./copy_mini_ntuples_to_project $1
  cd ..
done
