#!/bin/sh
#
# merge histogram-files
#
# input variables
#
# $1: version of data (subdir)
# $2: path and name of merged histogram-file
#
if [ -z $1 ]; then
    echo ""
    echo "Please give data-version"
    echo ""
    echo "Usage: merge [version] [outputname]"
    echo ""
    exit
fi
#
if [ -z $2 ]; then
    echo ""
    echo "Please give merged histogram-file"
    echo ""
    echo "Usage: merge [version] [outputname]"
    echo ""
    exit
fi
#
for dir in b c lf jpsi psiprime upsilon bh 
do
echo "Merging $dir"
cd $dir
./merge $1 $2
cd ..
done
