#!/bin/sh
#
# generate_mini_ntuples
#
# script runs analysis and prduces for each sample a mini-ntuple
# script generates project in $GUTCODEDIR named mini_$1
# and copies minintuples in respective directories
#
# input variables
#
# $1: project name (subdir in $GUTDATADIR)
# $2: name of template card for evlist generation
# $3: name of template card for mini-ntuple generation
#
if [ -z $1 ]; then
    echo ""
    echo "Please give project, template for evlist generation and template for mini-ntuple generation "
    echo ""
    echo "Usage: analyse [project] [evlist-template] [mini-nutple-template]"
    echo ""
    exit
fi
if [ -z $2 ]; then
    echo ""
    echo "Please give project, template for evlist generation and template for mini-ntuple generation "
    echo ""
    echo "Usage: analyse [project] [evlist-template] [mini-nutple-template]"
    echo ""
    exit
fi
if [ -z $3 ]; then
    echo ""
    echo "Please give project, template for evlist generation and template for mini-ntuple generation "
    echo ""
    echo "Usage: analyse [project] [evlist-template] [mini-nutple-template]"
    echo ""
    exit
fi

# gen date
export date=`date +%y%m%d_%H%M%S`

# link project
echo "link $1 for date $date"
./link_mconly $1 $date

# generate evlist cards
echo "generate cards for $1 using template $2"
./generate_cards_mconly $1 $2

# # execute analysis
 echo "execute mini analysis for $1 for date $date"
 ./execute_mini_mconly $1 $date

# # generate mini-ntuple cards
 echo "generate cards for $1 using template $3"
 ./generate_cards_mconly $1 $3
# 
# # execute analysis
 echo "execute mini analysis for mini ntuple generation for $1 for date $date"
 ./execute_mini_mconly $1 $date
# 
# # copy mini-ntuples in project_dir
 echo "copy mini-ntuples for $1 in new project"
 ./copy_mini_ntuples_to_project_mconly $1

