#!/bin/sh
#
# generate cards
#
# input variables
#
#
# $1: version of data (subdir)
# $2: cards template
#
#
if [ -z $1 ]; then
    echo ""
    echo "Please give data-version and cards file template"
    echo ""
    echo "Usage: generate_cards [version] [template]"
    echo ""
    exit
fi
#
if [ -z $2 ]; then
    echo ""
    echo "Please give data-version and cards file template"
    echo ""
    echo "Usage: generate_cards [version] [template]"
    echo ""
    exit
fi
#
#
for ver in 99p-00p
do
  for dir in 1s_dir 2s_dir
  do
    if [ -d $ver/$dir/$1 ]; then
      echo "Generate $1 cards in $ver/$dir/$1 with template $2"
      cd $ver/$dir/$1
      ./generate_cards $2
      cd ../../..
    fi
  done
done
