#!/bin/sh

cp ../mini_HeraII_0304p_Data_MC_Dimuon_Finalversion_dimuon_0304p_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_dimuon
cp ../mini_HeraII_05e_Data_MC_Dimuon_Finalversion_dimuon_05e_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_dimuon
cp ../mini_HeraII_0607p_Data_MC_Dimuon_Finalversion_dimuon_0607p_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_dimuon
cp ../mini_HeraII_06e_Data_MC_Dimuon_Finalversion_dimuon_06e_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_dimuon

cp ../Extraction_Scripts/mergefiles.sh  ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_dimuon
cp ../Plotting_Scripts/Histogramm_Plotscript.sh ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_dimuon
cp ../Plotting_Scripts/withsubsets/dimuon/*.C ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_dimuon
