#!/bin/sh

cp ../mini_HeraII_0304p_Data_MC_Dimuon_Finalversion_secvtx_0304p_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_secvtx
cp ../mini_HeraII_05e_Data_MC_Dimuon_Finalversion_secvtx_05e_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_secvtx
cp ../mini_HeraII_0607p_Data_MC_Dimuon_Finalversion_secvtx_0607p_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_secvtx
cp ../mini_HeraII_06e_Data_MC_Dimuon_Finalversion_secvtx_06e_dbothistos/*.root ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_secvtx

cp ../Extraction_Scripts/mergefiles.sh  ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_secvtx
cp ../Plotting_Scripts/Histogramm_Plotscript.sh ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_secvtx
cp ../Plotting_Scripts/withsubsets/secvtx/*.C ../mini_HeraII_0307p_Data_MC_Dimuon_Finalversion_dbothistos_secvtx
